### DISCUSSION TITLE
What does error 'API access for api.github.com is not configured' means?

### DISCUSSION THREAD

**Discussion by lastoCHka42** [WeblateOrg/weblate#10226] [Q&A] [answered]
Hello! I'm trying to integrate self-hosted Weblate with GitHub public repository. I've deployed Weblate with environmental variables in docker-compose.override.yml:
```
      WEBLATE_SERVER_EMAIL: 
      WEBLATE_DEFAULT_FROM_EMAIL: 
      WEBLATE_SITE_DOMAIN: 
      WEBLATE_ADMIN_PASSWORD: 
      WEBLATE_ADMIN_EMAIL: 
      WEBLATE_GITHUB_CREDENTIALS: "{'https://api.github.com': {'username': '', 'token': ''}}"     
```

I've set the PAT access to the full repo access, added SSH key (first tried RSA, then tried Ed25519) as a Deploy key in repo settings (with write access).
After that, I've imported my GitHub project via CLI:

```
weblate import_project --name-template 'Documentation: %s' \
> --file-format po --vcs 'github' \
> pro git@github.com:tarantool/doc.git latest \
> 'locale/*/LC_MESSAGES/**.po'
```

Project imported successfully. I've added some translations, committed them and tried to push via GUI:
![image](https://github.com/WeblateOrg/weblate/assets/88746790/9cbe5cfb-bd23-4b97-b931-a670c8ba2b4a)

As a result, I'm getting the error `GitHub pull request API access for api.github.com is not configured`. What does this error means? How can I fix it?

In the target remote repo, I can see that the Deploy key was used:
![image](https://github.com/WeblateOrg/weblate/assets/88746790/5cdc73e8-cf1c-4b87-95fb-dcd784bc404d)

I've seen the discussion #6765, but this doesn't work for me, or I do something wrong.
