### DISCUSSION TITLE
how to upgrade weblate to 5.0.2 version in docker

### DISCUSSION THREAD

**Discussion by gs-xpeng** [WeblateOrg/weblate#10539] [General]
how to upgrade weblate to 5.0.2 version in docker? 
we installed weblate 5.0.1 with docker, we wanted to upgrade to the latest version with docker compose pull, but failed. we need to upgrade to 5.0.2 first.  so how to upgrade weblate to 5.0.2 version in docker?  Thanks

**Comment by nijel** [comment]
Specify that version in docker-compose.yaml:

```yaml
services:
  weblate:
    image: weblate/weblate:5.0.2.2
```

You can search tags at https://hub.docker.com/r/weblate/weblate/tags?page=1&name=5.0.2
