### DISCUSSION TITLE
Reverse proxy by Nginx

### DISCUSSION THREAD

**Discussion by SanmerDev** [WeblateOrg/weblate#10727] [Q&A]
I run an Nginx service by docker (host all my sites on one server), but weblate (run in docker) always displays 502 Bad Gateway.

* docker-compose.override.yml
```yml
version: '3'
services:
  weblate:
    ports:
      - 8080:8080
    volumes:
      - ./config/gnupg/:/app/data/home/.gnupg
    environment:
      WEBLATE_EMAIL_HOST: ***
      WEBLATE_EMAIL_HOST_PASSWORD: ***
      WEBLATE_EMAIL_HOST_USER: ***
      WEBLATE_SERVER_EMAIL: ***
      WEBLATE_DEFAULT_FROM_EMAIL: ***
      
      WEBLATE_SITE_TITLE: ***
      WEBLATE_SITE_DOMAIN: weblate.sanmer.dev
      
      WEBLATE_ADMIN_NAME: ***
      WEBLATE_ADMIN_PASSWORD: ***
      WEBLATE_ADMIN_EMAIL: ***
      
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
      WEBLATE_SECURE_PROXY_SSL_HEADER: HTTP_X_FORWARDED_PROTO,https
      #WEBLATE_ENABLE_HTTPS: 1
      
      #WEBLATE_REGISTRATION_OPEN: 1
      #WEBLATE_REGISTRATION_ALLOW_BACKENDS: 'github'
      
      WEBLATE_SOCIAL_AUTH_GITHUB_KEY: ***
      WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: ***
      
      WEBLATE_GITHUB_USERNAME: ***
      WEBLATE_GITHUB_TOKEN: ***
      WEBLATE_GITHUB_HOST: api.github.com
      
      WEBLATE_GPG_IDENTITY: ***
      WEBLATE_DEFAULT_COMMITER_NAME: ***
      WEBLATE_DEFAULT_COMMITER_EMAIL: ***
      
```
* [weblate.log](https://github.com/WeblateOrg/weblate/files/13834636/weblate.log)

* nginx.conf
```conf
user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {   
    server {
        listen 443 ssl;
        server_name weblate.sanmer.dev;
        
        ssl_certificate /etc/nginx/ssl/weblate_sanmer_dev/weblate.sanmer.dev.crt;
        ssl_certificate_key /etc/nginx/ssl/weblate_sanmer_dev/weblate.sanmer.dev.key;

        location / {
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_pass http://127.0.0.1:8080;
        }
    }
}
```

* [nginx.log](https://github.com/WeblateOrg/weblate/files/13834645/nginx.log)
