### DISCUSSION TITLE
weblate-docker - CSRF verification failed

### DISCUSSION THREAD

**Discussion by bombitmanbomb** [WeblateOrg/weblate#11558] [Q&A]
I am trying to set up a weblate instance for several projects. Every time we try to login or register however, the page shows the following error:
```
Permission Denied
CSRF verification failed. Request aborted.
```
I've been looking through the documentation and forums, and have seen something about configuring a settings.py, but no such file exists.

I have the following config set up in the docker-compose.override.yml
```yml
version: '3'
services:
  weblate:
    ports:
      - 3045:8080
    environment:
      WEBLATE_NO_EMAIL_AUTH: true
      WEBLATE_ENABLE_HTTPS: false 
      WEBLATE_ADMIN_PASSWORD: REDACTED
      WEBLATE_ADMIN_EMAIL: REDACTED
      WEBLATE_SITE_DOMAIN: REDACTED
      WEBLATE_ALLOWED_HOSTS: REDACTED
      WEBLATE_SOCIAL_AUTH_GITHUB_KEY: REDACTED
      WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: REDACTED
```

This stuff is not my specialty and I am not sure how to proceed.
