### DISCUSSION TITLE
Is the migration hanging?

### DISCUSSION THREAD

**Discussion by johnpangalos** [WeblateOrg/weblate#11723] [Q&A] [answered]
Hey,

We have just inherited a weblate server running version 3.9.1 (docker version 3.9.1-1), and we just moved it from a server to kube using the helm chart and setting the image tag property to `3.9.1-1`. 

This seems to work, but now we're trying to upgrade weblate to version 4.0.4 (docker version 4.0.4-5) and we are running into issues. We get kube to start the docker container and it seems to connect to the postgres instance but after that it seems to hang. Here are the logs we get:

```
Starting...
weblate
Postgres is up
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 5.5.5.
        HINT: https://docs.weblate.org/en/weblate-4.0.4/admin/upgrade.html
Starting database migration...
```

We have had the same results with version 3.11.3 as well. Is this normal behavior? I was expecting more logs to as what the migration is doing.

Here is our helm chart:

```yaml
# Helm chart reference:
# https://artifacthub.io/packages/helm/weblate/weblate
emailHost: <Redacted>
emailPort: 587
emailTLS: true
emailSSL: false
emailUser: <Redacted>

defaultFromEmail: <Redacted>
serverEmail:  <Redacted>
adminEmail:  <Redacted>

persistence:
  size: 100Gi

image:
  tag: 3.9.1-3

service:
  type: NodePort

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: <Redacted>
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - <Redacted>
      secretName: <Redacted>

extraConfig:
  WEBLATE_LOGLEVEL: DEBUG

externalSecretName: external-secret
existingSecret: existing-secret

postgresql: 
  enabled: false
  postgresqlHost: <Redacted>
  auth:
    existingSecret: existing-secret
    database: weblate
    enablePostgresUser: true
  service:
    ports:
      postgresql: 5432

redis:
  auth:
    existingSecret: existing-secret

resources:
  limits:
    cpu: 4
    memory: 10Gi
  requests:
    cpu: 2
    memory: 8Gi

livenessProbe:
  initialDelaySeconds: 72000
  periodSeconds: 30
  failureThreshold: 10
```
