### DISCUSSION TITLE
Questions about uploading zip of yaml or po with pot file

### DISCUSSION THREAD

**Discussion by Sharlikran** [WeblateOrg/weblate#15273] [Q&A]
## sample files

[client_yaml.zip](https://github.com/user-attachments/files/20910471/client_yaml.zip)
[locale.zip](https://github.com/user-attachments/files/20910472/locale.zip)

## upload

How can I format a zip file that will simply and easily work by just uploading the file?

## attempted

I tried yaml monolingual with two files, and po

## also attempted

```yaml
client:
  SI_ABANDON_HOME_CAMPAIGN_FREE:
    en: "This change is free, however, future changes may incur a cost in Alliance Points or gold."
    kr: "襴 绀溽襀 紴竌襴诀篌, 襴飄 辔渀 绀溽襀 蟰革 闬襸钸血 滨盜筼 莌粨革瓈瓤."
  SI_ABANDON_HOME_CAMPAIGN_LOCKED_MESSAGE:
    en: "Your home campaign is currently locked since it has been changed recently.\n\nYou must wait <<1>> before being able to abandon it."
    kr: "瓹蓠襘 顈 邠閘襸襀 轜濼蟐 绀溽瘘滠 覅覥鞈褼緀穜 頄覬 覠溨覈蒵瓈瓤.\n\n|cffffff<<1>>|r 筼 闬瀰靠萘 覈襄 睌 灌诀 瀰瓤稤蝼 革瓈瓤."
``` 

I tried yaml with two languages but there was no dropdown for multi language file for YAML.

## searched, but I'm not using from scratch

https://github.com/orgs/WeblateOrg/discussions/5577

I did see that issue but I'm not using from scratch. I'm trying to simply upload a file, already complete, and already to go with all the files. Mainly because the files are partially translated.

## what I'm experencing

When I try to upload the local.zip for po it errors if I don't have a pot file. I provided the pot file and now it is telling me I have duplicate strings.

![image](https://github.com/user-attachments/assets/636ce0ac-20ba-4f48-a73f-a5d9a7132ea5)

Normally when I uploaded to ESOKR I was on that screen to add a new translation component and I browsed to a zip file like the ones I provided.

## next steps

https://hosted.weblate.org/projects/esokr/#languages

![image](https://github.com/user-attachments/assets/1ae021ea-2aeb-4361-ac7d-efaf9e2032b1)

I'm seeing this after error notifications and waiting a bit so I guess what I thought didn't work just took a while? Why would it error if it takes time. That's not intuitive. I'd have been less concerned if it said my zip was sorta okay but not perfect and we are working on it.

![image](https://github.com/user-attachments/assets/fcf04d2d-6e15-4003-9c29-0eb3d15aa006)

![image](https://github.com/user-attachments/assets/e7ae7d85-ca0c-47fb-aab8-2b24ec213062)

I want to upload other files, how do I do that, there is no upload from files or manage

## translation goal for all projects

![image](https://github.com/user-attachments/assets/c12abed6-9d6a-48c7-93de-d3f243793a06)

Why is there no English string so people can see it? Would using the multi lingual yaml provide that?

```
msgid "SI_ABANDON_HOME_CAMPAIGN_FREE"
msgstr "This change is free, however, future changes may incur a cost in Alliance Points or gold."

msgid "SI_ABANDON_HOME_CAMPAIGN_LOCKED_MESSAGE"
msgstr "Your home campaign is currently locked since it has been changed recently.\\n\\nYou must wait <<1>> before being able to abandon it."
```

I want users to see the SI_ABANDON_HOME_CAMPAIGN_FREE and see both english and korean at the same time where english is readonly and korean is what they edit for the translation.

**Comment by nijel** [comment]
The YAML files should work, but there is a syntax error in the file.

Weblate fails with:

> Could not parse translation base file: 'expected <block end>, but found \'<scalar>\' in "<unicode string>", line 7121, column 19:\n SI_KEYCODE105: "\'"\n ^ (line: 7121)'

The problematic section in the file:

```yaml
  SI_KEYCODE103: "\"
  SI_KEYCODE104: ';'
  SI_KEYCODE105: "'"
```

The `\` character escapes the double quote, what makes the quoted string contain all up to the next double quote.

**Comment by Sharlikran** [comment]
Part of the reason for my question to contain both yaml and po files is because of my issues with escaping characters.

I will be able to try again at about 17:00 UTC -8 so I will post the error and provide a different file.

Basically I was uploading the file over and over and towards the end, before switching to po files, no matter what line from the problematic lines I listed, removing the line with the \ just meant that the ; failed or the "'" (double quote, single quote, double quote) and so on.

I was removing the lines because I figured I would just try to use the interface in the web browser to add the few I had removed for the upload.

I'll try tye yaml files again later this evening.

**Reply by nijel** [reply]
You can try tools like https://www.yamllint.com/

**Reply by Sharlikran** [reply]
I tried that and it removed the double quotes. Which might be better to get it to upload onto the site but in the end I need the strings to be in key = "string" format. I'm still trying to understand or see how I can upload files that will work for translation and then download them to convert into the localization files.

**Comment by Sharlikran** [comment]
I don't remember the exact message so I want to provide the error later but it was something like double scaler.

**Comment by Sharlikran** [comment]
The lint website and what you mentioned got me looking into what I am doing when I generate the files with python for weblate from the game's files from the developers. So it is probably more my mistake there. 

I appreciate your time in reading this. I'd like to have it closed.

However  I'd like to reopen it this weekend if I can't get the files properly formatted, and if I'm still having trouble uploading the files.

I still want to get them uploaded and see if it's going to be formatted how I am hoping for.

**Comment by Sharlikran** [comment]
Because I have not had a successful upload with a successful display of the strings I'm still mentioning both formats as I talk through this to try and decide how to do everything.

```yaml
---
version: "1"
projects:
  - slug: eso-ui
    name: ESO UI Translations
    components:
      - slug: turkish-client
        name: Client - Turkish
        filemask: client.*.yaml
        monolingual_base_language: en
        monolingual_source_field: english
        monolingual_target_field: turkish
        source_file: client.en.yaml
        language: tr
      - slug: ukrainian-client
        name: Client - Ukrainian
        filemask: client.*.yaml
        monolingual_base_language: en
        monolingual_source_field: english
        monolingual_target_field: ukraine
        source_file: client.en.yaml
        language: uk
```
If I try to create that how do I get that in the right place so weblate can use it from my web browser? Or do I try uploading a zip with the file in the root and then the client.en.yaml or client.uk.yaml and so on and set the proper file mask etc.

I'm still trying to find a way to display the English and the translated string at the same time and also have the key like SI_KEYCODE104 to import the translation updates into the game files. Which is why I'm still going back and forth between po and yaml because I don't know yet which will be easier to configure and easier to use once someone updates the translation.
