### DISCUSSION TITLE
Unable to login as admin on Docker

### DISCUSSION THREAD

**Discussion by hajnyon** [WeblateOrg/weblate#7112] [Q&A] [answered]
Hello,
I wanted to try Weblate using docker. I started Weblate instance following the documentation, but I'm unable to login as admin. I tried few setups of password and username, restarting and removing volumes but with no luck. Is there some setting I'm missing? Does the email host have to be working? Logs seems ok, just few errors regarding not setup email host and warnings about DEBUG in production etc (I can provide the log if necessary). `docker-compose.override.yml` follows.

```yml
version: '3'
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_DEBUG: 1
      WEBLATE_EMAIL_HOST: smtp.example.com
      WEBLATE_EMAIL_HOST_USER: user
      WEBLATE_EMAIL_HOST_PASSWORD: pass
      WEBLATE_SERVER_EMAIL: weblate@example.com
      WEBLATE_DEFAULT_FROM_EMAIL: weblate@example.com
      WEBLATE_SITE_DOMAIN: weblate.example.com
      WEBLATE_ADMIN_PASSWORD: password
      WEBLATE_ADMIN_EMAIL: weblate.admin@example.com

```
