### DISCUSSION TITLE
Getting "OSError: [Errno 99] Cannot assign requested address" on registration

### DISCUSSION THREAD

**Discussion by AwesomeStickz** [WeblateOrg/weblate#7242] [Q&A]
So I tried to register in my weblate and I used to get SMTPAuthenticationError, it got fixed today when I tried config file from someone else and it did finally send me an email today on registering but when I later tried to change the server email and then registered, I got the following error:

```
Failed to send notifications: OSError: [Errno 99] Cannot assign requested address
```

Then I tried back the email which worked and it still gives me the same error, I tried googling and it didn't really help me much, so asking it here

My `docker-compose.override.yml` looks like this:

```
version: '3'
services:
  weblate:
    ports:
      - 9999:8080
    environment:
      WEBLATE_EMAIL_HOST: mail.domain.com
      WEBLATE_EMAIL_PORT: 587
      WEBLATE_EMAIL_USE_TLS: 1
      WEBLATE_EMAIL_USE_SSL: 0
      WEBLATE_EMAIL_USER: translate@domain.com
      WEBLATE_EMAIL_PASSWORD: password
      WEBLATE_EMAIL_HOST_USER: translate@domain.com
      WEBLATE_EMAIL_HOST_PASSWORD: password
      WEBLATE_SERVER_EMAIL: translate@domain.com
      WEBLATE_DEFAULT_FROM_EMAIL: translate@domain.com
      WEBLATE_ADMIN_EMAIL: admin@domain.com
      WEBLATE_ADMIN_PASSWORD: admin password
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_SITE_DOMAIN: translate.domain.com
  ```
