### DISCUSSION TITLE
Weblate in Portainer

### DISCUSSION THREAD

**Discussion by joergklein** [WeblateOrg/weblate#9671] [Q&A]
I would like to get Weblate working using Portainer. Unfortunately, all my attempts have failed so far. In the repository of Weblate there are several docker-compose files and a docker-compose.override.yml. I need some clarification on how to run Weblate in Portainer. I would like to use Gmail for sending mails from Weblate out.

**Comment by nijel** [comment]
Portainer seems to be based on Kubernetes, so why not to use https://docs.weblate.org/en/latest/admin/install/kubernetes.html?

**Reply by joergklein** [reply]
Portainer works with a simple docker-compose.yaml and an .env file. Portainer uses so-called "stacks". All you have to do is copy the docker-compose.yaml into it. Installing Helm and Kubernetes is not useful in my case.

**Reply by nijel** [reply]
That was just a question as I know nothing about that and their website says "Portainer: Docker and Kubernetes Management Platform".

Anyway, there should be no problem picking up either docker-compose.yml or docker-compose-https.yml (whether you want it to include HTTPS termination) and deploy it. Whether the environment file is named `.env` or `environment` is not relevant. See also https://docs.weblate.org/en/latest/admin/install/docker.html#installation

**Reply by joergklein** [reply]
I have changed the docker-compose.yaml and .env file. Weblate doesn't start. Please take a look on it. 
```

# my portainer stack config for weblate

version: "3.8"
services:
  weblate:
    ports:
      - '85:8585'
    image: weblate/weblate    
    tmpfs:
      - /run
      - /tmp
    volumes:
      - weblate-data:/app/data
      - weblate-cache:/app/cache
    restart: always
    read_only: true
    depends_on:
      - database
      - cache
    environment:
      - WEBLATE_DEBUG
      - WEBLATE_LOGLEVEL
      - WEBLATE_SITE_TITLE
      - WEBLATE_ADMIN_NAME
      - WEBLATE_ADMIN_EMAIL
      - WEBLATE_ADMIN_PASSWORD
      - WEBLATE_SERVER_EMAIL
      - WEBLATE_DEFAULT_FROM_EMAIL
      - WEBLATE_ALLOWED_HOSTS
      - WEBLATE_REGISTRATION_OPEN
      - WEBLATE_TIME_ZONE
      - WEBLATE_REQUIRE_LOGIN
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE
      - POSTGRES_HOST
      - POSTGRES_PORT
      - REDIS_HOST
      - REDIS_PORT
      - WEBLATE_EMAIL_HOST
      - WEBLATE_EMAIL_HOST_USER
      - WEBLATE_EMAIL_HOST_PASSWORD
      - WEBLATE_SITE_DOMAIN
      
  database:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DATABASE
      - POSTGRES_HOST
      - POSTGRES_PORT
    
  cache:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", --save, '60', '1']
    volumes:
      - redis-data:/data
volumes:
  weblate-cache: {}
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```
```

.env
WEBLATE_DEBUG=1
WEBLATE_LOGLEVEL=DEBUG
WEBLATE_SITE_TITLE=Weblate
WEBLATE_SITE_DOMAIN=lang.example.com
WEBLATE_ADMIN_NAME=Weblate Admin
WEBLATE_ADMIN_EMAIL=example@gmail.com
WEBLATE_ADMIN_PASSWORD=geheim
WEBLATE_SERVER_EMAIL=example@gmail.com
WEBLATE_DEFAULT_FROM_EMAIL=example@gmail.com
WEBLATE_ALLOWED_HOSTS=*
WEBLATE_REGISTRATION_OPEN=1
WEBLATE_TIME_ZONE=Europe/Berlin
WEBLATE_REQUIRE_LOGIN=1
WEBLATE_EMAIL_HOST=smtp.gmail.com
WEBLATE_EMAIL_HOST_USER=example@gmail.com
WEBLATE_EMAIL_HOST_PASSWORD=geheim
POSTGRES_PASSWORD=geheim
POSTGRES_USER=weblate
POSTGRES_DATABASE=weblate
POSTGRES_HOST=weblate_db
POSTGRES_PORT=5432
REDIS_HOST=weblate_cache
REDIS_PORT=6379
```
