### DISCUSSION TITLE
Cannot send e-mail (Connection unexpectedly closed: timed out)

### DISCUSSION THREAD

**Discussion by uSkizzik** [WeblateOrg/weblate#9699] [Q&A]
Hi! I'm trying to setup Weblate using Docker and I'm having some issues related to emails. That being the fact it can't send an email on startup.

It's always the same error:
```
check stderr | CRITICALS:
check stderr | ?: (weblate.E003) Cannot send e-mail (Connection unexpectedly closed: timed out), please check EMAIL_* settings.
check stderr |  HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#out-mail
```

It then continues to log health checks but connections get rejected.

Here's my docker override:
```yaml
version: '3'
services:
  weblate:
    ports:
      - 3030:3030
    environment:
      WEBLATE_EMAIL_HOST: 172.17.0.1
      WEBLATE_EMAIL_PORT: 25
      WEBLATE_EMAIL_HOST_USER: noreply@skizzium.com
      WEBLATE_EMAIL_HOST_PASSWORD: [redacted]
      WEBLATE_EMAIL_USE_SSL: 0
      WEBLATE_EMAIL_USE_TLS: 1
      WEBLATE_SERVER_EMAIL: noreply@skizzium.com
      WEBLATE_DEFAULT_FROM_EMAIL: noreply@skizzium.com
      WEBLATE_SITE_DOMAIN: translate.skizzium.com
      WEBLATE_ADMIN_PASSWORD: [redacted]
      WEBLATE_ADMIN_EMAIL: uskizzik@skizzium.com
 ```

My email service is hosted on the same machine that's hosting the docker containers. It does have SMTP enabled as I'm using it through Zammad (helpdesk hosted on the instance, connects to it via 127.0.0.1) and through my microservices (they're also using docker compose and use the same info to connect).

I have tried changing both SSL and TLS to true and false in all possible ways (both false, one true and one false) and I have also tried it with numbers (0 and 1). None of those worked.

Additionally I have tried connecting with the VPS's public IP. I know that's supposed to work as well because I tried sending an email through powershell and it worked.
