### ISSUE TITLE
Make it possible to add background images via local css

### ISSUE THREAD

**Issue by RheingoldRiver** [WeblateOrg/weblate#10342]
### Describe the problem

I want to write a local Stylus theme that, among other things, adds icons for several buttons, e.g. history icon for History, etc. But I can't do this because of Weblate's CSP, which is blocking my rule.

### Describe the solution you'd like

Alter the CSP to allow local styles to embed SVG background images.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/18037011/55ff14c0-2e3a-4528-9023-746229c573ee)

### Additional context

Here is the CSS I'm trying to run:

```css
#toggle-history::before {
    content:'';
        background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' height='20px' width='20px' %3E%3Cpath stroke-linecap='round' stroke-linejoin='round' d='M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z' /%3E%3C/svg%3E%0A")!important;
    display:inline-block;
    height:20px;
    width:20px;
}
```
