### ISSUE TITLE
Referenced images in CSS lead to CSP error https://hosted.weblate.org/static/sort/hover-down.svg

### ISSUE THREAD

**Issue by kozi** [WeblateOrg/weblate#10455]
### Describe the issue

The images

* https://github.com/WeblateOrg/weblate/blob/8a95d137363e29588dd7e6c269357dd4c5705a40/weblate/static/style-dark.css#L2186
* https://github.com/WeblateOrg/weblate/blob/8a95d137363e29588dd7e6c269357dd4c5705a40/weblate/static/style-dark.css#L2189

lead to a CSP error when using weblate as self hosted service.

![grafik](https://github.com/WeblateOrg/weblate/assets/464029/7129d4f6-cc33-4228-b3e4-22396697805e)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Open the developer tools in the browser
2. Refresh the weblate page.
3. CSP error is logged to the console.

### Expected behavior

The images should be embedded as data url in the css file.

It is possible to use https://yoksel.github.io/url-encoder/ so it is not necessary to encode the svg images as base64
```css
.icon {
/* up */
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8' version='1.1' viewBox='0 0 8 8'%3E%3Crect width='5.651' height='.706' x='-1.592' y='4.068' fill='%231fa385' fill-rule='evenodd' stroke-width='.706' transform='matrix(-.70711 .70711 .70711 .70711 0 0)'/%3E%3Crect width='.706' height='5.651' x='-1.592' y='4.068' fill='%231fa385' fill-rule='evenodd' stroke-width='.706' transform='matrix(-.70711 .70711 .70711 .70711 0 0)'/%3E%3Cscript xmlns=''/%3E%3C/svg%3E");
}
```

```css
/* down */
.icon {
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8' version='1.1' viewBox='0 0 8 8'%3E%3Crect width='5.651' height='.706' x='-1.593' y='-7.246' fill='%231fa385' fill-rule='evenodd' stroke-width='.706' transform='matrix(.70711 -.70711 -.70711 -.70711 0 0)'/%3E%3Crect width='.706' height='5.651' x='-1.593' y='-7.246' fill='%231fa385' fill-rule='evenodd' stroke-width='.706' transform='matrix(.70711 -.70711 -.70711 -.70711 0 0)'/%3E%3C/svg%3E");
}
```

### How do you run Weblate?

Docker container
