### ISSUE TITLE
Template to run weblate on Kubernetes

### ISSUE THREAD

**Issue by tswast** [WeblateOrg/weblate#1205]
This would be very similar to and/or use the [Docker-based deployment](https://docs.weblate.org/en/latest/admin/deployments.html?highlight=docker#deployment).

Instead of the `docker-compose` commands and configuration there would be the equivalent `kubectl` commands and configuration. This isn't to say that the two are mutually exclusive, I'm proposing an additional way to deploy.

Would the project be amenable to this? I may be able to contribute, if so.
##

**Comment by nijel** [comment]
Would that fit into https://github.com/WeblateOrg/docker repository? I'm definitely not against it.

**Comment by nijel** [comment]
PS: The Docker setup will change quite a lot soon (hopefully today), see https://github.com/WeblateOrg/docker/pull/13

**Comment by tswast** [comment]
Yeah, looks like it could work in https://github.com/WeblateOrg/docker, as it should just be some additional YAML files.

After thinking about this for a bit, I'm actually wondering what it might take to run on an even more managed service like Heroku or Google App Engine, though that'd be a separate issue. I'm thinking I might want to work on that first. I want to be as [serverless](http://martinfowler.com/bliki/Serverless.html) as I can be.

**Comment by HimanshuJanbandhu** [comment]
Hi, I would like to help on this, please help me get started, this is my first issue, Thankyou

**Comment by mleneveut** [comment]
Hi @HimanshuJanbandhu, I am working on this too on my side.

I created a deployment yaml for weblate, and I try to use the stable charts for Postgresql and redis.

But weblate complains about redis not found. Stuck here.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weblate-data
  namespace: common
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  namespace: common
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weblate
  labels:
    app: weblate
  namespace: common
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: weblate
    spec:
      containers:
      - image: weblate/weblate
        name: weblate
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        env:
        - name: WEBLATE_LOGLEVEL
          value: "debug"
        - name: WEBLATE_SITE_TITLE
          value: "Dekra translations"
        - name: WEBLATE_ADMIN_NAME
          value: "Weblate Admin"
        - name: WEBLATE_ADMIN_EMAIL
          value: "myemail"
        - name: WEBLATE_ADMIN_PASSWORD
          value: "mypwd"
        - name: WEBLATE_SERVER_EMAIL
          value: "myemail"
        - name: WEBLATE_DEFAULT_FROM_EMAIL
          value: "weblate@weblate.com"
        - name: WEBLATE_ALLOWED_HOSTS
          value: "*"
        - name: WEBLATE_REGISTRATION_OPEN
          value: "0"
        - name: POSTGRES_HOST
          value: "postgresql-postgresql"
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: WEBLATE_EMAIL_HOST
          value: 
        - name: WEBLATE_EMAIL_USER
          value: 
        - name: WEBLATE_EMAIL_PASSWORD
          value: 
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: /app/data
          name: weblate-data
      volumes:
        - name: weblate-data
          persistentVolumeClaim:
           claimName: weblate-data
---
apiVersion: v1
kind: Service
metadata:
  name: weblate
  labels:
    app: weblate
  namespace: common
spec:
  selector:
    app: weblate
  ports:
  - name: http
    port: 80
  type: ClusterIP
```

```
helm install stable/redis --namespace common --name redis --set rbac.create=true,password="mypwd",persistence.enabled=true,persistence.existingClaim="redis-data",master.resources.requests.memory=256Mi,master.resources.requests.cpu=10m,master.resources.requests.memory=1Gi,master.resources.requests.cpu=100m,master.persistence.storageClass=aksci
helm install stable/postgresql --namespace common --name postgresql --set postgresqlUsername=weblate,postgresqlPassword=weblate,postgresqlDatabase=weblate,persistence.storageClass=default,resources.requests.cpu=10m,image.tag=9.6
```

```
redis is unavailable - sleeping
-NOAUTH Authentication required.
+OK
redis not running!

redis is expected to run as separate Docker container.
```

**Comment by nijel** [comment]
The Weblate docker container is not currently accepting Redis password, that's why it doesn't work. I've drafted how it could work in https://github.com/WeblateOrg/docker/pull/166, testing is welcome.

**Comment by mleneveut** [comment]
@nijel I used the new edge build you made 3h ago, and I think including https://github.com/WeblateOrg/docker/pull/166, but I still have the Redis error.

```
Containers:
  weblate:
    Container ID:   docker://c7f44260dd292f3dd6f55a6c2b96307b7db39a44f613831de447707da9bcc41d
    Image:          weblate/weblate:edge
    Image ID:       docker-pullable://weblate/weblate@sha256:3488748ba9839069f659992aa3f5c2ce5d95ca2a6c7c0dbb74573865efe5a6ee
...
Environment:
      WEBLATE_LOGLEVEL:              debug
      WEBLATE_SITE_TITLE:           Weblate
      WEBLATE_ADMIN_NAME:            Weblate Admin
      WEBLATE_ADMIN_EMAIL:           redated
      WEBLATE_ADMIN_PASSWORD:        redated
      WEBLATE_SERVER_EMAIL:          redated
      WEBLATE_DEFAULT_FROM_EMAIL:    redated
      WEBLATE_ALLOWED_HOSTS:         *
      WEBLATE_REGISTRATION_OPEN:     0
      POSTGRES_HOST:                 postgresql-postgresql
      REDIS_HOST:                    redis-master
      REDIS_PORT:                    6379
      REDIS_PASSWORD:                redated
```

```
redis is unavailable - sleeping
-NOAUTH Authentication required.
+OK
redis not running!

redis is expected to run as separate Docker container.
```

**Comment by nijel** [comment]
I did only test that it doesn't break the no password case, that's why I've said that testing is welcome :-). Might be caused by using environment which is not supported by the redis-cli version used as it was introduced quite recently in https://github.com/antirez/redis/commit/f24ad5d83140eee04bd1cda8ee19bced0de26c11

**Comment by denyo** [comment]
Here you can find a working helm chart: https://github.com/denyo/docker-compose/tree/master/k8s
To deploy it simply run `helm upgrade weblate ./k8s --install`

**Comment by mleneveut** [comment]
working, thanks. The usePassword: false did the trick :)

**Comment by nijel** [comment]
The password should work fine with latest Weblate Docker, I've just merged https://github.com/WeblateOrg/docker/pull/152

**Comment by nijel** [comment]
Helm chart is available here: https://github.com/WeblateOrg/docker-compose/pull/8

**Comment by melalj** [comment]
For those who land on this, here's a template that worked for me (after hours of debugging...)

## 0-pvc.yml
```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblate-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

## 1-deploy.yml
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblate
  labels:
    app: weblate
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: weblate
  template:
    metadata:
      labels:
        app: weblate
        redis-client: "true"
    spec:
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      containers:
      - image: weblate/weblate
        name: weblate
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
        - name: WEBLATE_DEBUG
          value: "0"
        - name: WEBLATE_LOGLEVEL
          value: "INFO"
        - name: WEBLATE_SITE_TITLE
          value: "Weblate translations"
        - name: WEBLATE_ADMIN_NAME
          value: "Admin"
        - name: WEBLATE_ADMIN_EMAIL
          value: "admin@email.com"
        - name: WEBLATE_ADMIN_PASSWORD
          value: "********"
        - name: WEBLATE_SERVER_EMAIL
          value: "weblate@email.com"
        - name: WEBLATE_DEFAULT_FROM_EMAIL
          value: "weblate@email.com"
        - name: WEBLATE_ALLOWED_HOSTS
          value: "*"
        - name: WEBLATE_REGISTRATION_OPEN
          value: "0"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_USER
          value: "weblate"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          value: "****"
        - name: POSTGRES_DATABASE
          value: "weblate"
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PASSWORD
          value: "******"
        - name: "REDIS_DB"
          value: "2"
        - name: WEBLATE_EMAIL_HOST
          value: "smtp.sendgrid.net"
        - name: WEBLATE_EMAIL_HOST_USER
          value: "apikey"
        - name: WEBLATE_EMAIL_HOST_PASSWORD
          value: "*******"
        - name: WEBLATE_IP_PROXY_HEADER
          value: "HTTP_X_FORWARDED_FOR"
        resources:
          requests:
            cpu: 10m
            memory: 500Mi
          limits:
            cpu: 400m
            memory: 2000Mi
        volumeMounts:
        - mountPath: /app/data
          name: weblate-data
      volumes:
        - name: weblate-data
          persistentVolumeClaim:
           claimName: weblate-data
```

## 2-svc.yml
```yml
apiVersion: v1
kind: Service
metadata:
  name: weblate
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: weblate
```

**Comment by nijel** [comment]
Thanks @melalj, can you please contribute it as pull request to Weblate? I'm not sure where would be place people would be looking for this...

**Comment by mleneveut** [comment]
Here is mine on Azure AKS with Azure Redis and Keycloak. Had to stick to 3.8.5 due to communication problem with Azure Redis with higher versions.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weblate-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weblate
  labels:
    app: weblate
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: weblate
    spec:
      containers:
      - image: weblate/weblate:3.8-5
        name: weblate
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        env:
        - name: WEBLATE_DEBUG
          value: "False"
        - name: WEBLATE_LOGLEVEL
          value: "INFO"
        - name: WEBLATE_SITE_TITLE
          value: "Weblate"
        - name: WEBLATE_ADMIN_NAME
          value: "Weblate Admin"
        - name: WEBLATE_ADMIN_EMAIL
          value: "admin@company.com"
        - name: WEBLATE_ADMIN_PASSWORD
          value: "xxx"
        - name: WEBLATE_SERVER_EMAIL
          value: "noreply@company.com"
        - name: WEBLATE_DEFAULT_FROM_EMAIL
          value: "noreply@company.com"
        - name: WEBLATE_ALLOWED_HOSTS
          value: "*"
        - name: WEBLATE_ENABLE_HTTPS
          value: "True"
        - name: POSTGRES_HOST
          value: "xxx.postgres.database.azure.com"
        - name: POSTGRES_USER
          value: "weblate@xxx.postgres.database.azure.com"
        - name: POSTGRES_DATABASE
          value: "weblate"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-db
        - name: REDIS_HOST
          value: xxx.redis.cache.windows.net
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "xxx"
        - name: REDIS_TLS
          value: "false"
        - name: REDIS_VERIFY_SSL
          value: "true"
        - name: WEBLATE_EMAIL_HOST
          value: xxx
        - name: WEBLATE_EMAIL_USER
          value: xxx
        - name: WEBLATE_EMAIL_PASSWORD
          value: "xxx"
        - name: WEBLATE_SOCIAL_AUTH_KEYCLOAK_KEY 
          value: weblate
        - name: WEBLATE_SOCIAL_AUTH_KEYCLOAK_SECRET 
          value: "xxx"
        - name: WEBLATE_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY 
          value: "xxx"
        - name: WEBLATE_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL 
          value: https://keycloak.company.com/auth/realms/develop/protocol/openid-connect/auth
        - name: WEBLATE_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL 
          value: https://keycloak.company.com/auth/realms/develop/protocol/openid-connect/token
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - mountPath: /app/data
          name: weblate-data
        - mountPath: /app/data/ssl
          name: certificates
        - mountPath: /app/data/settings-override.py
          subPath: settings-override.py
          name: settings-override
      volumes:
        - name: weblate-data
          persistentVolumeClaim:
           claimName: weblate-data
        - name: certificates
          secret:
            secretName: tls-secret-is4
        - configMap:
            name: weblate-configmap
          name: settings-override
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: weblate
  labels:
    app: weblate
spec:
  selector:
    app: weblate
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
data:
  settings-override.py: |
    SOCIAL_AUTH_VERIFY_SSL = False
    SECURE_HSTS_SECONDS = 1209600
kind: ConfigMap
metadata:
  labels:
    application: weblate
  name: weblate-configmap
```

**Comment by tehKapa** [comment]
I also added liveness and readiness probe. I found this reference here https://docs.weblate.org/en/weblate-3.10/admin/install.html#monitoring-weblate

```
lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 5"
          livenessProbe:
            httpGet:
              path: /healthz/
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz/
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
```

Unfortunately I had to make a compromise.. which was to set the variable ALLOWED_HOSTS to *
```
- name: WEBLATE_ALLOWED_HOSTS
   value: "*"
```
