### ISSUE TITLE
Outgoing email is not working

### ISSUE THREAD

**Issue by ZiYueCommentary** [WeblateOrg/weblate#12335]
### Describe the issue

I planning to use a Microsoft 365 (Office E5) account to send emails. But weblate gives me `(weblate.E003) Cannot send e-mail ([Errno 99] Cannot assign requested address), please check EMAIL_* settings.`

I tried to specify an IP for `WEBLATE_EMAIL_HOST` and I got `(weblate.E003) Cannot send e-mail (timed out), please check EMAIL_* settings.`. The domain and IP are available when using `ping` command, and the configuration itself is confirmed as no issue.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Configure as:
```yml
WEBLATE_EMAIL_HOST: smtp.office365.com
WEBLATE_EMAIL_HOST_USER: weblate@ziyuesinicization.site
WEBLATE_EMAIL_HOST_PASSWORD: password
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.7
 * Django: 5.0.8
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.3
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.6
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.4.0
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.13.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * Python: 3.12.5
 * Git: 2.39.2
 * psycopg: 3.2.1
 * psycopg-binary: 3.2.1
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.160
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.8.1
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 52.96.42.66
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.0-30-amd64 (x86_64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail (timed out), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-5.7/admin/install.html#out-mail
?: (weblate.E012) The server e-mail address should be changed from its default value
        HINT: https://docs.weblate.org/en/weblate-5.7/admin/install.html#production-email
?: (weblate.E013) The "From" e-mail address should be changed from its default value
        HINT: https://docs.weblate.org/en/weblate-5.7/admin/install.html#production-email

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.7/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.7/admin/backup.html
```

### Additional context

Website URL: https://weblate.ziyuesinicization.site/

Server location: Hong kong

I'm using Cloudflare Proxy to let website support https.

Full configuration:
```yml
version: '3'
services:
  weblate:
    ports:
      - 80:8080
      - 443:4431
    environment:
      WEBLATE_EMAIL_HOST: smtp.office365.com
      WEBLATE_EMAIL_HOST_USER: weblate@ziyuesinicization.site
      WEBLATE_EMAIL_HOST_PASSWORD: password
      WEBLATE_AUTO_UPDATE: True
      #WEBLATE_SERVER_EMAIL: weblate@ziyuesinicization.site
      #WEBLATE_DEFAULT_FROM_EMAIL: weblate@ziyuesinicization.site
      WEBLATE_SITE_DOMAIN: weblate.ziyuesinicization.site
      WEBLATE_ALLOWED_HOSTS: weblate.ziyuesinicization.site
      WEBLATE_ADMIN_PASSWORD: password
      WEBLATE_ADMIN_NAME: 子悦解说
      WEBLATE_SITE_TITLE: ZiYue Weblate
      WEBLATE_SOCIAL_AUTH_GITHUB_KEY: key
      WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: secret
      WEBLATE_SOCIAL_AUTH_GITLAB_KEY: key
      WEBLATE_SOCIAL_AUTH_GITLAB_SECRET: secret
      WEBLATE_ADMIN_EMAIL: ziyuecommentary@gmail.com
      WEBLATE_ENABLE_SHARING: True
      WEBLATE_ENABLE_HTTPS: True
      WEBLATE_MATOMO_URL: url
      WEBLATE_MATOMO_SITE_ID: 7
      WEBLATE_GITHUB_USERNAME: ZiYueWeblate
      WEBLATE_GITHUB_TOKEN: token
      WEBLATE_GITHUB_HOST: api.github.com
      WEBLATE_DEFAULT_COMMITER_EMAIL: weblate@ziyuesinicization.site
      WEBLATE_DEFAULT_COMMITER_NAME: ZiYue Weblate
```
