### ISSUE TITLE
(weblate.C040) Include hostname only in the AZURE_DEVOPS_CREDENTIALS keys: https://dev.azure.com

### ISSUE THREAD

**Issue by Aspyryan** [WeblateOrg/weblate#12538]
### Describe the issue

I cannot get azure pull requests to work since the documentation does not provide full insight. I have put the following in my docker-compose.override.yml: 
```
version: "3"
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_EMAIL_HOST: smtp.example.com
      WEBLATE_EMAIL_HOST_USER: user
      WEBLATE_EMAIL_HOST_PASSWORD: pass
      WEBLATE_SERVER_EMAIL: weblate@example.com
      WEBLATE_DEFAULT_FROM_EMAIL: weblate@example.com
      WEBLATE_SITE_DOMAIN: weblate.example.com
      WEBLATE_ADMIN_PASSWORD: <REDACTED>
      WEBLATE_ADMIN_EMAIL: weblate.admin@example.com
      WEBLATE_AZURE_DEVOPS_USERNAME: proof of concepts # <-- this does have spaces
      WEBLATE_AZURE_DEVOPS_ORGANIZATION: org
      WEBLATE_AZURE_DEVOPS_TOKEN: <REDACTED>
      WEBLATE_AZURE_DEVOPS_HOST: https://dev.azure.com
```

I tried several different combinations but none seem to work. When leaving host I get
`ValueError: Incomplete AZURE_DEVOPS_CREDENTIALS configuration: missing WEBLATE_AZURE_DEVOPS_HOST` but when leaving it in I get error above.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Follow installation manual at: https://docs.weblate.org/en/weblate-5.7.2/admin/install/docker.html#installation
2. Add the override settings as above

### Expected behavior

Project to start or good documentation available

### How do you run Weblate?

Docker container
