### ISSUE TITLE
High Memory Usage Leading to OOM Error in Kubernetes Deployment of Weblate

### ISSUE THREAD

**Issue by tonyzhu** [WeblateOrg/weblate#13142]
### Describe the issue

I am deploying Weblate using the Docker image weblate/weblate:5.8.4.0 on Kubernetes. The deployment is configured with the following resource limits:

CPU: 2 cores
Memory: 7 GB
I observed that the memory usage of the Weblate pod quickly rises above 90% and eventually crashes with an OOM (Out of Memory) error within a day. Here are the relevant environment variables configured:

```yaml
Name:             WEBLATE_DEBUG
Value:            0
Name:             WEBLATE_WORKERS
Value:            16
Name:             WEB_WORKERS
Value:            4
Name:             RATELIMIT_LOCKOUT
Value:            180
Name:             RATELIMIT_ATTEMPTS
Value:            10
```
### Observed Behavior:
The pod crashes with an OOM error after running for less than a day.
Memory usage consistently stays above 90%.
### Question:
Is there a potential memory leak in the program?
Are there any recommended configuration changes to optimize memory usage for this setup?
Additional Information:
The container image was pulled from Docker Hub: weblate/weblate:5.8.4.0
Kubernetes resource limits:
```yaml
Resources:
  Limits:
    Cpu:     2000m
    Memory:  7Gi
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

oom

### How do you run Weblate?

Docker container

### Weblate versions

5.8.4.0
