### ISSUE TITLE
Format of matched files could not be recognized.

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1351]
### Steps to reproduce
1. Create new component
2. Pick "Ruby YAML" as the file format.
3. HTTPS GitHub repo

### Actual behaviour
Error: "Format of 7 matched files could not be recognized. config/locales/br.yml config/locales/de.yml config/locales/es.yml config/locales/it.yml config/locales/pl.yml config/locales/pt.yml config/locales/tr.yml"

### Expected behaviour
All files should be recognized?

### Server configuration
 * Weblate weblate-2.11-44-g92090bf
 * Python 2.7.12
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.1.0
 * social-auth-app-django 1.0.1
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.0
 * compressor 2.0
 * djangorestframework 3.5.3
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.7.3
 * hub 2.3.0-pre8-28-gfe5b59b
 * Database backends: django.db.backends.postgresql_psycopg2

### Misc
Strange that it doesn't complain about the file `en.yml`.

en.yml:

```
en:
  language: 'English'
  number:
    format:
      separator: ','
      delimiter: '.'
  ... etc
```

But complains about:
de.yml:

```
de:
  language: 'Deutsch'
  number:
    format:
      separator: ','
      delimiter: '.'
  ... etc
```

**Comment by nijel** [comment]
I've often seen problems with translations using boolean keys - Weblate accepts only strings. In Yaml there is quite lot of strings which translate to boolean (see http://yaml.org/type/bool.html):  `y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF`

Do you happen to have some keys named like these?

**Comment by Frexuz** [comment]
No. Here are the full files:

en.yml: https://gist.github.com/Frexuz/fb3ec62b9b30149f101f32b0cfdda770

de.yml: https://gist.github.com/Frexuz/90a79c9188b0ec544dc56a6948ce4ad8

There are non strings, like:  
```
  time:
    am: am
    pm: pm

or 

    day_names:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
```
However, the admin did not complain about this in the `en` file.
