### ISSUE TITLE
Cannot send e-mail

### ISSUE THREAD

**Issue by koori0831** [WeblateOrg/weblate#13577]
### Describe the issue

I'm setting up Weblate with docker-compose and trying to get HTTPS working using Certbot. I've successfully generated the certificates, but Weblate is reporting "OSError: [Errno 99] Cannot assign requested address" when trying to send emails. I'm using Gmail's SMTP server and have configured the WEBLATE_EMAIL_* environment variables in my docker-compose.yml file, including an app password. I've also set SERVER_EMAIL and DEFAULT_FROM_EMAIL. Network connectivity from the Weblate container seems fine as I can ping external hosts. I'm not sure what's causing the email sending issue.
```yml
services:
  weblate:
    image: weblate/weblate
    container_name: weblate
    ports:
      - "8080:8080"
    volumes:
      - weblate_data:/app/data
    environment:
      - WEBLATE_SITE_DOMAIN=<My DomainName>
      - WEBLATE_ADMIN_EMAIL=MyID@gmail.com
      - WEBLATE_ADMIN_PASSWORD=<password>
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=weblate
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weblate
      - CACHES_REDIS_HOST=cache
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=MyID@gmail.com
      - EMAIL_HOST_PASSWORD=<appcord>
      - EMAIL_USE_TLS=True
      - EMAIL_USE_SSL=False
      - SERVER_EMAIL=MyID@gmail.com
      - DEFAULT_FROM_EMAIL=MyID@gmail.com
    depends_on:
      - db
      - cache
    restart: unless-stopped
    networks:
      - weblate_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weblate
    networks:
      - weblate_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 5; done'"

  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=weblate
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weblate
    networks:
      - weblate_net

  cache:
    image: redis:latest
    container_name: redis
    networks:
      - weblate_net

volumes:
  certbot_letsencrypt:
  certbot_www:
  postgres_data:
  weblate_data:

networks:
  weblate_net:
```

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. run the command docker-compose up -d

2. access weblate externally and login with your admin account

3. click send test email on the admin page

4. take a log and it will show the same error repeatedly.

### Expected behavior

I just want my team members to be able to log in to weblate! so I want to use Gmail SMTP over TLS.

### Exception traceback

```pytb

```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.9.2
 * Django: 5.1.5
 * siphashc: 2.5
 * translate-toolkit: 3.14.5
 * lxml: 5.3.0
 * pillow: 11.1.0
 * nh3: 0.2.20
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * RapidFuzz: 3.11.0
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.2
 * translation-finder: 2.19
 * weblate-language-data: 2024.16
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20241021
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.1.0
 * sentry-sdk: 2.19.2
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.44
 * borgbackup: 1.4.0
 * pyparsing: 3.2.1
 * ahocorasick_rs: 0.22.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.4.1
 * cyrtranslit: 1.1.1
 * drf-spectacular: 0.28.0
 * Python: 3.12.8
 * Git: 2.39.5
 * psycopg: 3.2.3
 * psycopg-binary: 3.2.3
 * phply: 1.2.6
 * ruamel.yaml: 0.18.10
 * tesserocr: 2.7.1
 * boto3: 1.35.98
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.7
 * google-cloud-translate: 3.19.0
 * openai: 1.59.6
 * Mercurial: 6.9
 * git-svn: 2.39.5
 * git-review: 2.4.0
 * PostgreSQL server: 15.10
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.6.51+rpt-rpi-v8 (aarch64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno 99] Cannot assign requested address), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-5.9.2/admin/install.html#out-mail
?: (weblate.E012) The server e-mail address should be changed from its default value
        HINT: https://docs.weblate.org/en/weblate-5.9.2/admin/install.html#production-email
?: (weblate.E013) The "From" e-mail address should be changed from its default value
        HINT: https://docs.weblate.org/en/weblate-5.9.2/admin/install.html#production-email

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.9.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.9.2/admin/backup.html

System check identified 8 issues (34 silenced).
```
