### ISSUE TITLE
WEBLATE_PRE_COMMIT_SCRIPTS Docker support

### ISSUE THREAD

**Issue by GuillaumeAmat** [WeblateOrg/weblate#1506]
I'm trying to set up a Weblate instance and I would like to use the `/app/examples/hook-generate-mo` pre-commit hook, but it doesn't show up in the component admin page select.

My `docker-compose.override.yml` looks like that:

```
version: '2'
services:
  weblate:
    environment:
      - WEBLATE_DEBUG=1
      - WEBLATE_LOGLEVEL=DEBUG
      - WEBLATE_REGISTRATION_OPEN=0
      - WEBLATE_REQUIRE_LOGIN=1
      - WEBLATE_EMAIL_HOST=*****
      - WEBLATE_EMAIL_USER=*****
      - WEBLATE_EMAIL_PASSWORD=*****
      - WEBLATE_EMAIL_PORT=465
      - WEBLATE_ALLOWED_HOSTS=*****
      - WEBLATE_ADMIN_PASSWORD=*****
      - WEBLATE_OFFLOAD_INDEXING=1
      - WEBLATE_PRE_COMMIT_SCRIPTS=('/app/examples/hook-generate-mo')
```

The documentation does not talk about the `WEBLATE_PRE_COMMIT_SCRIPTS` variable for Docker but for Openshift. Is it supported on Docker? Am I missing something else?

Thank you!

### Steps to reproduce
1. Clone https://github.com/WeblateOrg/docker.git
2. Add the docker-compose.override.yml file below in the clone folder
3. Start Weblate
4. Go to the admin page, set a site, a project and a component
5. See the pre-commit select empty

### Actual behaviour
The pre-commit select is empty.

### Expected behaviour
The *hook-generate-mo* pre-commit hook is displayed in the pre-commit select.
