### ISSUE TITLE
translate-toolkit does not support configuring wrapper for po

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1867]
### Steps to reproduce
1. Just follow the Docker https setup, no other custom changes
2. Using git ssh repo. 2 components with **yaml** and **json** files respectively.

### Actual behaviour
When starting up, we get these errors/warnings in the **Performance report** page:

LAST OCCURRENCE | NAME | MESSAGE |  
-- | -- | -- | --
Feb. 22, 2018, 8:40 a.m. | File format: po-mono-unwrapped | Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/formats.py", line 103, in register_fileformat     fileformat.get_class()   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/formats.py", line 1034, in get_class     'translate-toolkit does not support configuring wrapper for po' ImportError: translate-toolkit does not support configuring wrapper for po |  
Feb. 22, 2018, 8:40 a.m. | File format: po-unwrapped | Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/formats.py", line 103, in register_fileformat     fileformat.get_class()   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/formats.py", line 1034, in get_class     'translate-toolkit does not support configuring wrapper for po' ImportError: translate-toolkit does not support configuring wrapper for po

### Expected behaviour
No errors :)

### Server configuration
```
version: '2'
services:
  weblate:
    environment:
      - WEBLATE_EMAIL_HOST=*****
      - WEBLATE_EMAIL_HOST_USER=*****
      - WEBLATE_EMAIL_HOST_PASSWORD=*****
      - WEBLATE_ALLOWED_HOSTS=*****
      - WEBLATE_ADMIN_PASSWORD=*****
      - WEBLATE_DEFAULT_FROM_EMAIL=*****
      - WEBLATE_DEBUG=0
      - WEBLATE_OFFLOAD_INDEXING=1
  https-portal:
    environment:
      DOMAINS: '*****.com -> http://weblate'
```
