### ISSUE TITLE
Skipping empty strings?

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1920]
Is it possible to skip empty-on-purpose translation strings?

This is a standard Rails yaml file:

```
en:
  number:
    human:
      decimal_units:
        format: "%n %u"
        units:
          billion: Billion
          million: Million
          quadrillion: Quadrillion
          thousand: Thousand
          trillion: Trillion
          unit: ''
      format:
        delimiter: ''
        significant: true
        strip_insignificant_zeros: true
      storage_units:
        format: "%n %u"
        units:
          byte:
            one: Byte
            other: Bytes
          gb: GB
          kb: KB
          mb: MB
          tb: TB
    percentage:
      format:
        delimiter: ''
    precision:
      format:
        delimiter: ''
```

A bit annoying needing to skip these every time, as well as always having a few "Strings needing actions"
![screen shot 2018-03-22 at 15 53 01](https://user-images.githubusercontent.com/49692/37757799-2295de5e-2de9-11e8-9534-2b2d386d20f1.png)
