### ISSUE TITLE
Indexing offloading processing fails?

### ISSUE THREAD

**Issue by Frexuz** [WeblateOrg/weblate#1931]
What does this mean? Can't find anything in the docs.

![screen shot 2018-03-23 at 19 11 07](https://user-images.githubusercontent.com/49692/37826369-2572a496-2ece-11e8-846f-63aa1fd28c7b.png)

docker-compose-https.override.yml
```
version: '2'
services:
  weblate:
    environment:
      - WEBLATE_EMAIL_HOST=example.com
      - WEBLATE_EMAIL_HOST_USER=test
      - WEBLATE_EMAIL_HOST_PASSWORD=password
      - WEBLATE_ALLOWED_HOSTS=translate.example.com
      - WEBLATE_ADMIN_PASSWORD=password
      - WEBLATE_DEFAULT_FROM_EMAIL=hello@example.com
      - WEBLATE_DEBUG=0
      - WEBLATE_OFFLOAD_INDEXING=1
  https-portal:
    environment:
      DOMAINS: 'translate.example.com -> http://weblate'
```

crontab
```
*/5 * * * * cd /usr/share/weblate/; docker-compose run --rm weblate update_index
@daily cd /usr/share/weblate/; docker-compose run --rm weblate cleanuptrans
@hourly cd /usr/share/weblate-docker/; docker-compose run --rm weblate commit_pending --all --age=96
```
