### ISSUE TITLE
On default docker install web pages periodically hang

### ISSUE THREAD

**Issue by wjdp** [WeblateOrg/weblate#2271]
**Describe the bug**
Pages often hang while loading and often never fully finish loading. Periodically (every 5-10 minutes) the server will stop fielding requests and all attempts to navigate are met with 'infinite loading'. After a minute or two pages start loading again.

**To Reproduce**
1. Create a Weblate deployment using the method described in the documentation.
2. Use the following `docker-compose.override.yml`.
```yaml
version: '2'
services:
  weblate:
    environment:
      - WEBLATE_DEBUG=0
      - WEBLATE_SERVER_EMAIL=noreply@example.com
      - WEBLATE_DEFAULT_FROM_EMAIL=noreply@example.com
      - WEBLATE_ALLOWED_HOSTS=translations.int.mycompany.io
      - WEBLATE_REQUIRE_LOGIN=1
      - WEBLATE_REGISTRATION_OPEN=0
      - WEBLATE_SITE_TITLE=Translations
```

**Expected behavior**
A smooth experience navigating between pages on the web UI.

**Screenshots**
Most of the time all pages stay in the loading state after the page has loaded:

![image](https://user-images.githubusercontent.com/1690934/46030518-465c3e80-c0ee-11e8-92c6-01874be09ee6.png)

**Server configuration and status**

```
docker-compose exec weblate weblate list_versions

 * Weblate 3.1.1
 * Python 3.5.3
 * Django 2.0.8
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 4.15.0-1019-aws (x86_64)
```

Running `docker-compose exec weblate weblate check --deploy` yields nothing, terminal just hangs and needs a `^C` to get back to a prompt.

![image](https://user-images.githubusercontent.com/1690934/46030863-43158280-c0ef-11e8-83e9-f74e8ddda0a5.png)

**Additional context**
We are operating behind an HTTP/HTTPS proxy. Docker is configured for this proxy as per https://docs.docker.com/config/daemon/systemd/#httphttps-proxy.
