### ISSUE TITLE
Support for Golang's i18n Formats

### ISSUE THREAD

**Issue by panbanda** [WeblateOrg/weblate#2558]
**Is your feature request related to a problem? Please describe.**

I would love to see support for Golang's i18n support.  I use hugo a lot and the yaml/json/toml i18n configs are great but they are unique to golang.  

**Describe the solution you'd like**

Can we support at least go-i18n-json or yaml formats?  It would be great to do toml formats as well but the low hanging fruit seems to be the json/yaml formats.

https://github.com/nicksnyder/go-i18n

```yaml
- id: translation-key
  translation: translation goes here
```

```json
[
  { 
    "id": "translation-key", 
    "translation": "translation goes here" 
  }
]
```

```toml
[translation-key]
other = "Translation goes {{.Here}}"
```

**Comment by nijel** [comment]
Preferably the support would be first integrated in the [translate-toolkit](https://github.com/translate/translate/), supporting it then in Weblate is easy.

Rant: Why does every toolchain come with own way of storing localization? There is already enough of them ;-).

**Comment by eighthave** [comment]
@panbanda does Hugo/Go really only support that one format? It looks like a bad format, without much support for very valuable things that PO and XLIFF support, like developer comments, character limits, etc.  Seems to me the right solution here is to make Hugo/Go support a full featured, standard translation file format.  Right now, it looks like they are just reinventing the wheel, and doing it poorly at that.

**Comment by eighthave** [comment]
@matrixcoffee and I will need to follow this, could you add it to the Linguine tracker?

**Comment by nijel** [comment]
I don't think it makes much difference implementing yaml or toml based format. And anything but toml doesn't seem to handle plurals, or am I missing something?

Actually is there some documentation for the formats? I was only able to find some examples, but really no specification...

**Comment by panbanda** [comment]
@nijel it does handle plurals but in a kind of (IMO) awkward way:

```
[readingTime]
one = "One minute read"
other = "{{.Count}} minutes read"
```

So if just defining something normally it would be "other" by default.

**Comment by panbanda** [comment]
> @panbanda does Hugo/Go really only support that one format? It looks like a bad format, without much support for very valuable things that PO and XLIFF support, like developer comments, character limits, etc. Seems to me the right solution here is to make Hugo/Go support a full featured, standard translation file format. Right now, it looks like they are just reinventing the wheel, and doing it poorly at that.

I'm with you.  I really enjoy Hugo for static sites but find the i18n stuff lacking.  Maybe in the future I can build a lib that uses more standardized flow...

**Comment by nijel** [comment]
It's quite clear how plurals are handled in toml, my question was more about json/yaml, who are present only with id/translation in the examples.

**Comment by panbanda** [comment]
@nijel ah my bad yeah I understand.  The test data there actually has the JSON and YAML formats if you're interested in seeing them.  But TLDR: It's basically the same structured format if you can imagine turning the TOML into YAML.

https://github.com/nicksnyder/go-i18n/tree/master/goi18n/testdata

```yaml
- id: person_greeting
  translation: "Hello {{.Person}}"

- id: my_height_in_meters
  translation:
    one: "I am {{.Count}} meter tall."
    other: "I am {{.Count}} meters tall."

# Also according to their testdata
person_greeting:
  other: "Hello {{.Person}}"

my_height_in_meters:
  one: "I am {{.Count}} meter tall."
  other: "I am {{.Count}} meters tall."
```

JSON:

```json
{
  "person_greeting": {
    "other": "Hello {{.Person}}"
  },

  "my_height_in_meters": {
    "one":  "I am {{.Count}} meter tall.",
    "other":  "I am {{.Count}} meters tall."
  },
}
```
