### ISSUE TITLE
SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by vburghelea** [WeblateOrg/weblate#2679]
**Describe the bug**
When attempting to test the e-mail server configuration, Django reports "SMTP AUTH extension not supported by server."

**To Reproduce**
- weblate 3.5.1 installed and running via docker-compose
- configured connection to a [Mail-in-a-Box](https://mailinabox.email) setup on a freshly (and correctly) set-up domain
- under the Performance section, "weblate.E003 | Can not send email (SMTP AUTH extension not supported by server.), please check EMAIL_* settings."
- running the maintenance command docker-compose exec --user weblate weblate weblate sendtestemail email my_email@address does not function either

**Expected behavior**
Would have expected the system to work and not report issues

**Screenshots**
![Screenshot 2019-04-09 at 17 38 21](https://user-images.githubusercontent.com/1913582/55814215-62ee2000-5aee-11e9-9646-1050c8358f2c.png)
![Screenshot 2019-04-09 at 17 37 14](https://user-images.githubusercontent.com/1913582/55814217-62ee2000-5aee-11e9-8157-760bd20c2bac.png)

**Server configuration and status**
list_versions:
```
 * Weblate 3.5.1
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-46-generic (x86_64)
```
check --deploy:
```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email (SMTP AUTH extension not supported by server.), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#collecting-errors

System check identified 4 issues (0 silenced).
```

**Additional context**
My docker-compose.override file has the following settings:
```
version: '3'
services:
  weblate:
    environment:
      - WEBLATE_EMAIL_HOST=box.<domain>
      - WEBLATE_EMAIL_PORT=587
      - WEBLATE_EMAIL_USE_TLS=True
      - WEBLATE_EMAIL_USE_SSL=False
      - WEBLATE_EMAIL_USER=weblate@<domain>
      - WEBLATE_EMAIL_PASSWORD=<password>
      - WEBLATE_EMAIL_HOST_USER=weblate@<domain>
      - WEBLATE_EMAIL_HOST_PASSWORD=<password>
      - WEBLATE_SERVER_EMAIL=weblate@<domain>
      - WEBLATE_DEFAULT_FROM_EMAIL=weblate@<domain>
      - WEBLATE_ALLOWED_HOSTS=weblate.internal.<hosting_domain>,localhost
      - WEBLATE_ADMIN_PASSWORD=<admin_password>
      - WEBLATE_ADMIN_EMAIL=weblate@<domain>
      - WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=<google_oauth_key>
      - WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=<google_oauth_secret>
      - WEBLATE_ENABLE_HTTPS=1
```

I have attempted all permutations when it comes to WEBLATE_EMAIL_USE_TLS / WEBLATE_EMAIL_USE_SSL and have checked that TLS support is enabled and that the credentials are correct for AUTH LOGIN on the mail-in-a-box setup using `openssl s_client` - I don't know what else to do and was hoping someone could point me in the right direction...
