### ISSUE TITLE
Docker https configuration documentation is missing something; connection refused

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#2948]
After configuring to run in docker with https I am getting "connection refused"
While in non-https mode it runs fine.

docker-compose output:

```
Starting weblate-docker_cache_1        ... done
Starting weblate-docker_database_1     ... done
Starting weblate-docker_https-portal_1 ... done
Starting weblate-docker_weblate_1      ... done

...

https-portal_1  | 2019/08/08 12:00:26 [error] 290
#290: *1 connect() failed (111: Connection refused) while connecting to upstream, 
client: 111.3.2.1, server: translate.portal.com,
 request: "GET / HTTP/2.0", upstream: "http://172.1.2.3/", host: "translate.portal.com"
```

**docker-compose.yml**

```yml
version: '3'
services:
  weblate:
    image: weblate/weblate
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    environment:
      WEBLATE_ENABLE_HTTPS: 1
  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
    volumes:
      - ssl-certs:/var/lib/https-portal
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
  ssl-certs: {}
```

**docker-compose.override.yml**

```yml
version: '3'
services:
  weblate:
    environment:
      WEBLATE_EMAIL_HOST:
      WEBLATE_EMAIL_HOST_USER:
      WEBLATE_EMAIL_HOST_PASSWORD:
      WEBLATE_SERVER_EMAIL:
      WEBLATE_DEFAULT_FROM_EMAIL: 
      WEBLATE_ALLOWED_HOSTS: translate.portal.com,localhost,weblate
      WEBLATE_ADMIN_PASSWORD: 
      WEBLATE_ADMIN_EMAIL: 
  https-portal:
    environment:
      DOMAINS: 'translate.portal.com -> http://weblate'
```
