### ISSUE TITLE
ISO639-1 code should not be alias of regional sub-code

### ISSUE THREAD

**Issue by zypA13510** [WeblateOrg/weblate#3116]
**Describe the bug**
[Currently](https://github.com/WeblateOrg/weblate/blob/6aafd840d00e72c43737089dfe8ac5504810a6bf/weblate/langdata/languages.py#L831), `zh` is an alias of `zh_Hans` - Chinese (Simplified). And adding both `zh` and `zh_CN` will lead to a duplicate language alert:
> The component contains several translation files mapped to single language in Weblate.
> 
> Language | Language codes
> -- | --
> Chinese (Simplified) | zh_CN, zh

There are cases where having a `zh` file and a `zh_CN` file may be desired. For example, the framework I use will try to load `zh_CN` first, if not found, falling back to `zh`. Imagine if my project has `zh` and `zh_CN`, a visitor with language set to `zh_TW` would not find `zh_TW`, so he will fall back to `zh`. If only `zh_CN` exists, he will not have any localized resources to load (except the default, e.g. `en`).

I think this should also be true for other language codes too. There is a reason for regional sub-code to exist. At least, it should be configurable. Currently, this cannot even be manually overridden - I've tried adding a new language "Chinese" with language code "zh" in Weblate manually, but the alert is still there and no file is detected/associated with the new language.

Not sure if this is related to `SIMPLIFY_LANGUAGE` in any way, but it's set to 0 on my installation.

**To Reproduce**
1. Create a git project with `i18n/i18n.properties`, `i18n/i18n_en.properties`, `i18n/i18n_zh.properties` and `i18n/i18n_zh_CN.properties`
2. Create a new component in Weblate set to track the git project
3. Go to alerts.
4. See the above error.

**Expected behavior**
The following languages appear in Weblate:
- English (en)
- Chinese (zh)
- Chinese (Simplified) (zh_CN)

**Screenshots**

**Server configuration and status**
Deployed with docker-compose (click to expand).
<details><summary>docker-compose.override.yml</summary>

```
version: '2.2'
services:
  weblate:
    ports:
    - 8080:8080
    environment:
      WEBLATE_DEBUG: 0
      WEBLATE_LOGLEVEL: WARNING
      WEBLATE_ADMIN_NAME: John Doe
      WEBLATE_ADMIN_EMAIL: john.doe@example.com
      WEBLATE_ADMIN_PASSWORD: "●●●●●●●●"
      WEBLATE_SERVER_EMAIL: "\"Weblate\" <weblate-admin@example.com>"
      WEBLATE_DEFAULT_FROM_EMAIL: "\"Weblate\" <weblate@example.com>"
      WEBLATE_ALLOWED_HOSTS: "*"
      WEBLATE_REGISTRATION_OPEN: 0
      WEBLATE_TIME_ZONE: Asia/Hong_Kong
      WEBLATE_ENABLE_HTTPS: 0
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
      WEBLATE_SIMPLIFY_LANGUAGES: 0
      WEBLATE_MT_MYMEMORY_ENABLED: 1
      WEBLATE_MT_GLOSBE_ENABLED: 1
      WEBLATE_EMAIL_HOST: smtp.example.com
      WEBLATE_EMAIL_PORT: 25
      WEBLATE_EMAIL_USE_SSL: 0
      WEBLATE_EMAIL_USE_TLS: 0
```
</details>
<details><summary>list_versions</summary>

```
 * Weblate 3.9
 * Python 3.7.3
 * Django 2.2.6
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.7
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 6.2.0
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * tesserocr 2.4.1
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * hub 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.example.com
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.10.0-1062.1.2.el7.x86_64 (x86_64)
```
</details>
<details><summary>check --deploy</summary>

```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.8/admin/install.html#collecting-errors

System check identified 4 issues (1 silenced).
```
</details>
