### ISSUE TITLE
SSL problem in docker

### ISSUE THREAD

**Issue by roman-huliak** [WeblateOrg/weblate#3274]
Hi, 
I have new installation of weblate in docker using "https://docs.weblate.org/en/latest/admin/install/docker.html" docs.

From fresh install without configuration changes is problem with gravatar (info from performance)

``
weblate.E018 | Failed to download avatar: <urlopen error _ssl.c:1039: The handshake operation timed out>
``

Also checkout project repository from GIT. I tried HTTPS and SSH (with enabled ssh key) and request timeouted after 5 minutes. Repository size is approx. 1MB.

Where is problem?

docker-compose.override.yml
```
version: '3'
services:
  weblate:
    volumes:
      - /docker/data/weblate/weblate-data:/app/data
    ports:
      - 8081:8080
    environment:
      WEBLATE_DEBUG: 1
      WEBLATE_ALLOWED_HOSTS: weblate.example.com,localhost
  database:
    volumes:
      - /docker/data/weblate/postgres-data:/var/lib/postgresql/data
  cache:
    volumes:
      - /docker/data/weblate/redis-data:/data
```
