### ISSUE TITLE
Support arrays in YAML/JSON format

### ISSUE THREAD

**Issue by guoyunhe** [WeblateOrg/weblate#3796]
**Is your feature request related to a problem? Please describe.**
I am working on a Jekyll theme with a localization plugin. The plugin support date localization, but day and month names must be arrays. See https://github.com/openSUSE/jekyll-theme/blob/l10n-feat/_data/locales/en.yaml

I read Weblate [doc](https://docs.weblate.org/en/latest/formats.html#yaml-files) and it says only key-value pairs are supported, not arrays.

**Describe the solution you'd like**
Weblate could support arrays, treat item index as key.

**Describe alternatives you've considered**

**Additional context**

**Comment by nijel** [comment]
Arrays are supported, the docs is just unclear.

**Comment by erciccione** [comment]
Ae they? Because i'm having a number of issues with them. If an element changes position, all elements in the array will be displayed wrong on weblate.

**Comment by nijel** [comment]
Yes, they are supposed to work.

What do you mean by that? Like `[Sunday, Monday, Tuesday]` becoming `[Monday, Tuesday, Sunday]`?

**Comment by erciccione** [comment]
@nijel I had a problem with an array containing IRC channels + their decription (https://github.com/monero-project/monero-site/blob/master/_i18n/en.yml#L97)

When the position of one o fthe entries got changed, weblate couldn't parse the strings correctly and was showing the wrong description for the rooms.

To explain myself:

```yaml
- entry: 1
description: description of 1
- entry: 2
description: description for 2
- entry: 3
description: description for 2
```
was showing uncorrectly on Weblate. The description that should have been for 1, was showing for 2 and so on.

| English  | Translation  |
|---|---|
|  description of 1 | description of 2   |
| description of 2  |  description of 3  |
|  description of 3 |  description of 4  |

I thought this was caused by weblate identifying the array using their indexes. Weblate seems to suggest so, since the 'context' on the platform appears as `hangouts->irc_channels->[6]->description`.

I had a similar problem with another section with similar structure, where changing the location of one elements inside the nested yaml created the same behaviour i havedescribed above. I fixed the problem by simply changing the nested yaml into a simpler structure: https://github.com/monero-project/monero-site/pull/934 and i assumed the problem was related to weblate not being able to properly parse a complex structure. I thought that only the structure [shown here](https://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/yaml.html) was "safely" supported.

**Comment by nijel** [comment]
This will probably never work as expected, Weblate would have to understand that in this case "channel" should be used as key. You would have to define custom file format defining the behavior there.

Why not use it directly like a key?

```yaml
  irc_channels:
    monero: This channel is used to discuss all things Monero related.
    monero-community: This channel is for the Monero community to congretate and discuss ideas.
```
