### ISSUE TITLE
Nested YAML question 

### ISSUE THREAD

**Issue by ZoomImpulse** [WeblateOrg/weblate#3863]
Hi,

I've got YAMLs of different translations that look like this:

test_l_english.yml:
```
l_english:
 localisation_ID1: "EXAMPLETEXT"
 localisation_ID2: "EXAMPLETEXT"
 ...
```

test_l_german.yml:
```
l_german:
 localisation_ID1: "EXAMPLETEXT"
 localisation_ID2: "EXAMPLETEXT"
 ...
```

Is it possible to not differentiate between l_english and l_german context strings?
