### ISSUE TITLE
GitHub OAuth callback URL must be HTTP when use with Docker + Nginx

### ISSUE THREAD

**Issue by RikkaW** [WeblateOrg/weblate#4040]
I'm using Weblate with Docker. Since I have already using Nginx, there is no choice but to use Nginx's reverse proxy.

When using GitHub authentication, the problem comes. Since the reverse proxy is used, weblate will pass HTTP `redirect_uri` to GitHub (like `https://github.com/login/oauth/authorize?client_id=...&redirect_uri=http://...`). I have to set an HTTP callback URL in GitHub, or GitHub will return `redirect_uri_mismatch`.

docker-compose.yml:
```
version: '3'
services:
  weblate:
    ports:
      - 7000:8080
    environment:
      WEBLATE_REGISTRATION_ALLOW_BACKENDS: github
      WEBLATE_SOCIAL_AUTH_GITHUB_KEY: 
      WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: 
```

Nginx config:
```
server {
    listen 80;
    listen [::]:80;
    server_name ;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ;
    location / {
        proxy_set_header   Host      $http_host;
        proxy_pass         http://localhost:7000;
        proxy_redirect      off;
        proxy_set_header    X-Forwarded-Host	$server_name;
        proxy_set_header    X-Real-IP       	$remote_addr;
        proxy_set_header    X-Forwarded-For		$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto	$scheme;
    }
    ssl_certificate ;
    ssl_certificate_key ;
}
```
