### ISSUE TITLE
Cannot update site URL in docker deployment

### ISSUE THREAD

**Issue by radeklat** [WeblateOrg/weblate#4133]
**Describe the bug**

In a docker-based Weblate installation, I initially used the server IP address in [`WEBLATE_ALLOWED_HOSTS`](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ALLOWED_HOSTS). As part of productionizing the setup, I changed it to an actual URL `weblate.lat.sk`. However, the installation keeps insisting on using the IP address and reverts back on restart.

**To Reproduce**

1. Install Weblate using docker with WEBLATE_ALLOWED_HOSTS set to an IP address
2. Start Weblate
3. Update WEBLATE_ALLOWED_HOSTS to an URL
4. Update Site in Django admin / Sites to an URL
5. Run docker-compose restart

**Expected behavior**

The site is set to the URL

**Server configuration and status**

 * Weblate: 4.1.1
 * Django: 3.0.7
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.5
 * kombu: 4.6.10
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.6
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 1.4.6
 * Mercurial: 5.4.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.9
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-40-generic (x86_64)

**Weblate deploy checks**

```text
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Exception traceback**

```text
database_1  | 2020-07-05 11:18:59.794 UTC [67] ERROR:  duplicate key value violates unique constraint "django_site_domain_a2e37b91_uniq"
database_1  | 2020-07-05 11:18:59.794 UTC [67] DETAIL:  Key (domain)=(weblate.lat.sk) already exists.
database_1  | 2020-07-05 11:18:59.794 UTC [67] STATEMENT:  UPDATE "django_site" SET "domain" = 'weblate.lat.sk', "name" = 'weblate.lat.sk' WHERE "django_site"."id" = 1
```

However, when app containers start, I login to the database and run the same update statement, it passes without errors.

**Additional context**

When I set the site URL via Django Admin / Sites, it gets reverted back to the IP address on docker restart.
When I set the site URL via `docker-compose exec weblate weblate changesite --set-name weblate.lat.sk`, it gets reverted as well on restart.

Additionally, I have no idea where Weblate gets the IP address from as it is not present in any configuration file.

#### docker-compose.override.yml

```yaml
version: '3'
services:
  weblate:
    ports:
      - 8182:8080
      - 8183:4443
    environment:
      WEBLATE_EMAIL_HOST: smtp.***.com
      WEBLATE_EMAIL_HOST_USER: ***@***.com
      WEBLATE_EMAIL_HOST_PASSWORD: ***
      WEBLATE_EMAIL_PORT: ***
      WEBLATE_EMAIL_USE_TLS: 1
      WEBLATE_SERVER_EMAIL: ***@***.com
      WEBLATE_DEFAULT_FROM_EMAIL: ***@***.com
      WEBLATE_ALLOWED_HOSTS: weblate.lat.sk
      WEBLATE_ADMIN_PASSWORD: ***
      WEBLATE_ADMIN_EMAIL: ***@***.com
      WEBLATE_DEBUG: 0
      WEBLATE_SECURE_PROXY_SSL_HEADER: HTTP_X_FORWARDED_PROTO,https
      WEBLATE_ENABLE_HTTPS: 1
```

#### settings-override.py

In: `/var/lib/docker/volumes/weblate-docker_weblate-data/_data/settings-override.py`

```python
MT_SERVICES = (
#    'weblate.machinery.apertium.ApertiumAPYTranslation',
#    'weblate.machinery.deepl.DeepLTranslation',
#    'weblate.machinery.glosbe.GlosbeTranslation',
    'weblate.machinery.google.GoogleTranslation',
#    'weblate.machinery.microsoft.MicrosoftCognitiveTranslation',
#    'weblate.machinery.microsoftterminology.MicrosoftTerminologyService',
#    'weblate.machinery.mymemory.MyMemoryTranslation',
#    'weblate.machinery.tmserver.AmagamaTranslation',
#    'weblate.machinery.tmserver.TMServerTranslation',
#    'weblate.machinery.yandex.YandexTranslation',
#    'weblate.machinery.weblatetm.WeblateTranslation',
#    'weblate.machinery.saptranslationhub.SAPTranslationHub',
#    'weblate.memory.machine.WeblateMemory',
)

MT_GOOGLE_KEY="***"

SECURE_SSL_REDIRECT=True

SECURE_HSTS_PRELOAD=True
SECURE_HSTS_INCLUDE_SUBDOMAINS=True
SECURE_HSTS_SECONDS=63072000

SESSION_COOKIE_SECURE=True

SENTRY_DNS="https://***@***.ingest.sentry.io/***"
```
