### ISSUE TITLE
Authentication over ldap needs some logging

### ISSUE THREAD

**Issue by yennor** [WeblateOrg/weblate#4385]
**Is your feature request related to a problem? Please describe.**
I'm using the docker image of weblate and just lost about 45 minutes trying to setup the ldap authentication. In the ip address of the ldap server I've had a mistake. But since there wasn't a single error message in the log file (i've activated debug), I was playing around forever with the dn_templte, dn_search etc. settings (which by the way are pretty bad documented). I've needed to read through settings_docker.py to be sure how they work.
Now everything is working. But still there is not a single mentioning of ldap or authentication in the logs.

**Describe the solution you'd like**
Give some log output, especially when something isn't working.

**Comment by nijel** [comment]
In shipped example configuration verbose LDAP logging is enabled when DEBUG mode is set:

https://github.com/WeblateOrg/weblate/blob/53c42ab0ef4e16f6d76f8e5dd8d66d2449735be0/weblate/settings_example.py#L484-L485

Even without that, it should log errors. What is your logging configuration?

**Comment by yennor** [comment]
Nah, no support question. I've got everything working and am not planing to change the configuration again ;-).
My logging configuration is: 
services:
  weblate:
    environment:
      WEBLATE_DEBUG: 1

I can send you the whole log produced by docker if you want to. But I can guarantee you, there's no mention of ldap, dn, cn inside (that were the words I was grepping for).

**Comment by nijel** [comment]
On the other side, I've seen such logs in several cases :-). What version do you use? WEBLATE_LOGLEVEL not set?

**Comment by yennor** [comment]
I've just tried out:
      WEBLATE_DEBUG: 1
      WEBLATE_LOGLEVEL: DEBUG

and setting an invalid ldap server. => I can't log in ;-).
But not a single error message in the log file or any mentioning of ldap.
I'm using Weblate 4.2.1 with the current weblate docker-compose project. According to git pull it is uptodate.

**Comment by nijel** [comment]
Okay, just tried it, the log contains:

```
weblate_1   | uwsgi stderr | WARNING Caught LDAPError while authenticating fads: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'errno': 22, 'ctrls': [], 'info': 'Invalid argument'})
```

My `docker-compose.override.yml`:

```
version: '3'
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_SITE_DOMAIN: 127.0.0.1
      WEBLATE_AUTH_LDAP_SERVER_URI: ldap://ldap.example.org
      WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE: uid=%(user)s,ou=People,dc=example,dc=net
      WEBLATE_AUTH_LDAP_USER_ATTR_MAP: first_name:name,email:mail
```
