### ISSUE TITLE
Unable to get Github's Pull Request to work

### ISSUE THREAD

**Issue by doums** [WeblateOrg/weblate#4680]
Hi,

I'm trying to setup Weblate to create Pull Request on push.\
Note that direct push and pulls works fine.
The first problem I encounter is a contradiction between what is in the documentation and what I actually have in my current weblate instance (local container):

> In case you do not want direct pushes by Weblate, there is support for GitHub, GitLab pull requests or Gerrit reviews, you can activate these by choosing GitHub, GitLab or Gerrit as Version control system in Component configuration.

[doc](https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate)

But in my weblate app, under `Version control system`, "GitHub" is not present. This is the first problem.

Here is the `environment` part of my `docker-compose.yml`
```
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: weblate
      POSTGRES_PORT: 5432
      POSTGRES_USER: weblate
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WEBLATE_ADMIN_EMAIL: xxx.admin@example.com
      WEBLATE_ADMIN_NAME: admin
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_ALLOWED_HOSTS: "*"
      WEBLATE_DEFAULT_FROM_EMAIL: xxx@example.com
      WEBLATE_LOGLEVEL: DEBUG #dev only
      WEBLATE_REGISTRATION_OPEN: 0
      WEBLATE_SERVER_EMAIL: xxx@example.com
      WEBLATE_SITE_DOMAIN: xxx.example.com
      VCS_CLONE_DEPTH: 0
      GITHUB_TOKEN: xxxxx
```
