### ISSUE TITLE
Using own SSL Certificate with docker-compose

### ISSUE THREAD

**Issue by marknitek** [WeblateOrg/weblate#5858]
**Describe the issue**
I tried to follow the instructions on how to use your own ssl certificate but i'am struggling to get it to work. And i don't have any information about what is wrong. I can run the setup in http mode just fine but as soon as i add the `fullchain.pem` and `key.pem` files to the volume under ssl/* the endpoint refuses any connection (both http and https).
When i exec in the container and examine the permissions everything looks fine:
```
/app/data/ssl$ ls -l
total 16
-rw------- 1 weblate weblate 2382 Apr 15 07:26 fullchain.pem
-rw------- 1 weblate weblate 1854 Apr 15 11:34 privkey.pem
-rw-r--r-- 1 weblate weblate 2021 Apr 13 11:31 saml.crt
-rw------- 1 weblate weblate 3272 Apr 13 11:31 saml.key
```
How do i know if there is anything wrong with the cert or how to know if it is actually used/applied? I converted a .pfx to .pem and i'am not sure if i did it correctly. It had bag attributes which i removed manually, does that help?

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

**docker-compose.yml**
```
version: "3"
services:
  weblate:
    image: weblate/weblate
    volumes:
      - weblate_weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    environment: {}
  database:
    image: postgres:13-alpine
    env_file:
      - ./environment
    volumes:
      - weblate_postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - weblate_redis-data:/data
volumes:
  weblate_weblate-data: 
    external: true    
  weblate_postgres-data:
    external: true
  weblate_redis-data:
    external: true
```

**docker-compose.override.yml**
```
version: "3"
services:
    weblate: 
      ports:
        - 80:8080
        - 443:4443
      environment:        
        WEBLATE_EMAIL_HOST: ***
        WEBLATE_EMAIL_PORT: 25        
        WEBLATE_SERVER_EMAIL: ***
        WEBLATE_DEFAULT_FROM_EMAIL: ***
        WEBLATE_ALLOWED_HOSTS: 10.0.10.59,translate.***.ch
        WEBLATE_EMAIL_USE_SSL: 0
        WEBLATE_EMAIL_USE_TLS: 0
        # Required
        WEBLATE_SITE_DOMAIN: translate.***.ch
        WEBLATE_ADMIN_PASSWORD: ***
        WEBLATE_ADMIN_EMAIL: ***

        WEBLATE_MT_MICROSOFT_COGNITIVE_KEY: ***
       
        WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_KEY: ***
        WEBLATE_SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET: ***
```

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**

Docker

**Weblate deploy checks**

```
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.5.3/admin/backup.html

System check identified 3 issues (1 silenced).
```

**Additional context**
