### ISSUE TITLE
Weblate site unreachable after docker install

### ISSUE THREAD

**Issue by martijnmichel** [WeblateOrg/weblate#6073]
```
weblate_1   | check stderr | 
weblate_1   | check stderr | CRITICALS:
weblate_1   | check stderr | ?: (weblate.E003) Cannot send e-mail ((535, b'Incorrect authentication data')), please check EMAIL_* settings.
weblate_1   | check stderr |    HINT: https://docs.weblate.org/en/weblate-4.6.2/admin/install.html#out-mail
weblate_1   | check stderr | 
weblate_1   | check stderr | WARNINGS:
weblate_1   | check stderr | ?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
weblate_1   | check stderr | ?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
weblate_1   | check stderr | ?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
weblate_1   | check stderr | ?: (security.W018) You should not have DEBUG set to True in deployment.
weblate_1   | check stderr | 
weblate_1   | check stderr | INFOS:
weblate_1   | check stderr | ?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
weblate_1   | check stderr |    HINT: https://docs.weblate.org/en/weblate-4.6.2/admin/install.html#collecting-errors
weblate_1   | check stderr | ?: (weblate.I028) Backups are not configured, it is highly recommended for production use
weblate_1   | check stderr |    HINT: https://docs.weblate.org/en/weblate-4.6.2/admin/backup.html
weblate_1   | check stderr | 
weblate_1   | check stderr | System check identified 7 issues (1 silenced).
weblate_1   | 2021-05-24 11:49:25,427 INFO exited: check (exit status 1; expected)
weblate_1   | uwsgi stderr | [pid: 477|app: 0|req: 1/2] 127.0.0.1 () {32 vars in 353 bytes} [Mon May 24 11:49:49 2021] GET /healthz/ => generated 2 bytes in 590 msecs (HTTP/1.1 200) 8 headers in 304 bytes (1 switches on core 0)
weblate_1   | nginx stdout | 127.0.0.1 - - [24/May/2021:11:49:50 +0000] "GET /healthz/ HTTP/1.1" 200 12 "-" "curl/7.64.0"
weblate_1   | celery-celery stderr | [2021-05-24 11:50:12,349: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[05f2351f-0157-4464-95e8-c98a9e1e0f70]  
weblate_1   | uwsgi stderr | [pid: 471|app: 0|req: 2/3] 127.0.0.1 () {32 vars in 353 bytes} [Mon May 24 11:50:20 2021] GET /healthz/ => generated 2 bytes in 56 msecs (HTTP/1.1 200) 8 headers in 304 bytes (1 switches on core 0)
weblate_1   | nginx stdout | 127.0.0.1 - - [24/May/2021:11:50:20 +0000] "GET /healthz/ HTTP/1.1" 200 12 "-" "curl/7.64.0"
weblate_1   | uwsgi stderr | [pid: 471|app: 0|req: 3/4] 127.0.0.1 () {32 vars in 353 bytes} [Mon May 24 11:50:50 2021] GET /healthz/ => generated 2 bytes in 52 msecs (HTTP/1.1 200) 8 headers in 304 bytes (1 switches on core 0)
weblate_1   | nginx stdout | 127.0.0.1 - - [24/May/2021:11:50:50 +0000] "GET /healthz/ HTTP/1.1" 200 12 "-" "curl/7.64.0"
```
-->

**Describe the issue**

Can not reach the page because it says "This site can’t be reached" on the correct URL.

**I already tried**

Re-installing a few times with different email settings.

**To Reproduce the issue**

Install from docker like explained on the website.

**Expected behavior**

A reachable installation of weblate where I can login and adjust settings.

**Comment by nijel** [comment]
How does your docker compose configuration looks like? Probably port mapping is missing...

**Comment by martijnmichel** [comment]
This is my latest compose file, although I've tried the easiest (from website) and other solutions.
After starting weblate is not accessible from port 32140
```
version: '3'
services:
    weblate:
        ports:
                - 32140:32140
        environment:
            WEBLATE_EMAIL_HOST: mail.tocadovision.nl
            WEBLATE_EMAIL_HOST_USER: tocado1q
            WEBLATE_EMAIL_HOST_PASSWORD: ---
            WEBLATE_EMAIL_USE_SSL: 1
            WEBLATE_DEBUG: 0
            WEBLATE_ENABLE_HTTPS: 1
            WEBLATE_EMAIL_USE_TLS: 0
            WEBLATE_EMAIL_PORT: 465
            WEBLATE_SERVER_EMAIL: info@tocadovision.fake
            WEBLATE_DEFAULT_FROM_EMAIL: info@tocadovision.fake
            WEBLATE_SITE_DOMAIN: translate.sonid.app
            WEBLATE_ADMIN_PASSWORD: ---
            WEBLATE_ADMIN_EMAIL: info@tocadovision.fake
            WEBLATE_SECURE_PROXY_SSL_HEADER: HTTP_X_FORWARDED_PROTO,https
```
