### ISSUE TITLE
docker-compose local volume: /app/data/secret: Permission denied

### ISSUE THREAD

**Issue by xerenahmed** [WeblateOrg/weblate#6166]
I get this error when I say docker compose up, it didn't happen on my own mac os computer, but it happens on another linux computer.

```
...
database_1  | 2021-06-10 11:58:55.397 UTC [1] LOG:  database system is ready to accept connections
weblate_1   | /app/bin/start: 31: /app/bin/start: cannot create /app/data/secret: Permission denied
weblate_1   | Starting...
weblate_1   | Generating Django secret...
weblate_weblate_1 exited with code 2
....
```
-->

**Server configuration and status**

docker-compose.yml
```yml
version: "3"

services:
  weblate:
    image: weblate/weblate
    tmpfs:
      - /app/cache
    volumes:
      - ./data/weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    ports:
      - 80:8080

  database:
    image: postgres:13-alpine
    env_file:
      - ./environment
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
```

Directory Tree: (tree -L 3)
```tree
.
├── Makefile
├── README.rst
├── data
│   ├── postgres-data
│   │   ├── PG_VERSION
│   │   ├── base
│   │   ├── global
│   │   ├── pg_commit_ts
│   │   ├── pg_dynshmem
│   │   ├── pg_hba.conf
│   │   ├── pg_ident.conf
│   │   ├── pg_logical
│   │   ├── pg_multixact
│   │   ├── pg_notify
│   │   ├── pg_replslot
│   │   ├── pg_serial
│   │   ├── pg_snapshots
│   │   ├── pg_stat
│   │   ├── pg_stat_tmp
│   │   ├── pg_subtrans
│   │   ├── pg_tblspc
│   │   ├── pg_twophase
│   │   ├── pg_wal
│   │   ├── pg_xact
│   │   ├── postgresql.auto.conf
│   │   ├── postgresql.conf
│   │   └── postmaster.opts
│   └── weblate-data
├── docker-compose.yml
└── environment

20 directories, 10 files
```

ll data
```
-rw-r--r--  1 root root   13 Jun 10 11:45 .gitignore
drwx------ 19   70 root 4096 Jun 10 11:58 postgres-data/
drwxr-xr-x  2 root root 4096 Jun 10 11:58 weblate-data/
```
