### ISSUE TITLE
Add-ons not installed on Docker self-hosted weblate

### ISSUE THREAD

**Issue by jonko0493** [WeblateOrg/weblate#6738]
**Describe the issue**

After installing weblate through docker and specifying the add-ons I want in docker-compose.override.yml with `WEBLATE_ADD_ADDONS`, I do not see the "Add-ons" option under the "Manage" on the project screen and /api/addons returns:

```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
- [x] Booting weblate without the `WEBLATE_ADD_ADDONS` env variable
- [x] I've completely deleted all containers and volumes and started over from scratch

**To Reproduce the issue**

1. Install self-hosted weblate through docker as described in documentation
2. Set docker-compose.override.yml to
```
services:
        weblate:
                ports:
                        - 80:8080
                environment:
                        WEBLATE_EMAIL_HOST: redacted
                        WEBLATE_EMAIL_HOST_USER: redacted
                        WEBLATE_EMAIL_HOST_PASSWORD: redacted
                        WEBLATE_SERVER_EMAIL: redacted
                        WEBLATE_DEFAULT_FROM_EMAIL: redacted
                        WEBLATE_SITE_DOMAIN: 'redacted'
                        WEBLATE_ADMIN_PASSWORD: 'redacted'
                        WEBLATE_ADMIN_EMAIL: redacted
                        WEBLATE_ADD_ADDONS: weblate.consistency.languages,weblate.discovery.discovery,weblate.git.squash
```
3. Run `docker-compose up -d`
4. See problems described in web interface

**Expected behavior**

As described in the documentation, the API should show the list of installed add-ons to be the three I've specified and I should be able to go to Manage -> Addons in the project settings to add add-ons.

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: Docker

 * Weblate: 4.8.1
 * Django: 3.2.7
 * siphashc: 2.1
 * translate-toolkit: 3.4.1
 * lxml: 4.6.3
 * Pillow: 8.3.2
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.12.0
 * oauthlib: 3.1.1
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 58.2.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.9
 * celery: 5.1.2
 * kombu: 5.1.0
 * translation-finder: 2.10
 * weblate-language-data: 2021.5
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.0.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.3.1
 * Cython: 0.29.24
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.9.2
 * Git: 2.30.2
 * psycopg2: 2.9.1
 * psycopg2-binary: 2.9.1
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.16
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.18.54
 * zeep: 4.1.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.9.1
 * git-svn: 2.30.2
 * git-review: 2.1.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.19.0-18-cloud-amd64 (x86_64)
 
**Weblate deploy checks**

```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.8.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.8.1/admin/backup.html
```

**Additional context**

Results of `docker logs weblate-docker_weblate_1 | grep addon`:
```
Postgres is up
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, fonts, gitexport, glossary, lang, memory, metrics, screenshots, sessions, social_django, trans, utils, weblate_auth, wladmin
  Applying addons.0001_squashed_0021_linguas_daily... OK
  Applying addons.0002_cleanup_addon_events... OK
  Applying addons.0003_alter_event_event... OK
celery-celery stdout |   . weblate.addons.tasks.cdn_parse_html
celery-celery stdout |   . weblate.addons.tasks.daily_addons
celery-celery stdout |   . weblate.addons.tasks.language_consistency
celery-backup stdout |   . weblate.addons.tasks.cdn_parse_html
celery-backup stdout |   . weblate.addons.tasks.daily_addons
celery-backup stdout |   . weblate.addons.tasks.language_consistency
celery-notify stdout |   . weblate.addons.tasks.cdn_parse_html
celery-notify stdout |   . weblate.addons.tasks.daily_addons
celery-notify stdout |   . weblate.addons.tasks.language_consistency
celery-translate stdout |   . weblate.addons.tasks.cdn_parse_html
celery-translate stdout |   . weblate.addons.tasks.daily_addons
celery-translate stdout |   . weblate.addons.tasks.language_consistency
celery-memory stdout |   . weblate.addons.tasks.cdn_parse_html
celery-memory stdout |   . weblate.addons.tasks.daily_addons
celery-memory stdout |   . weblate.addons.tasks.language_consistency
uwsgi stderr | /usr/local/lib/python3.9/dist-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'weblate.addons.models.Addon'> AddonQuerySet.
```
