### ISSUE TITLE
How to use Weblate with Azure B2C and custom policy?

### ISSUE THREAD

**Issue by svdHero** [WeblateOrg/weblate#7885]
### Describe the issue

We have Azure B2C set up with a custom policy flow. We'd like to use this for login with Weblate. According to [this](https://python-social-auth.readthedocs.io/en/latest/backends/azuread.html) linked article from the documentation, one can use a B2C Tenant with the `WEBLATE_SOCIAL_AUTH_AZUREAD_B2C_OAUTH2_POLICY ` environment variable.

However, the [Weblate documentation](https://docs.weblate.org/en/latest/admin/auth.html?highlight=azure#microsoft-azure-active-directory) does not state what the name of the back-end should be, i.e. the value for the environment variable `WEBLATE_REGISTRATION_ALLOW_BACKENDS`.
Should one just use `azuread-tenant-oauth2` or is there something like `azuread-b2c-tenant-oauth2`?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by svdHero** [comment]
@nijel Thank you so much for that hint. How exactly would I do that in my case?
We run Weblate via a Docker Compose file on Azure App Service for Containers. The Docker Compose file looks like this:
```yaml
version: "3"
services:
  weblate:
    image: weblate/weblate
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - cache
    ports:
      - 80:8080
  cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  redis-data: {}
```
and all the settings are injected via environment variables (aka Application Settings) in Azure.

How would I overwrite the settings? Do I just create a new file `/app/data/settings-override.py` that only consists of
```python
AUTHENTICATION_BACKENDS = (
    "social_core.backends.azuread_b2c.AzureADB2COAuth2",
    "social_core.backends.email.EmailAuth",
    "weblate.accounts.auth.WeblateUserBackend",
)
```
and nothing else? Is that it?

And how would I put that file in the `weblate-data` volume via the Docker Compose file? Or do I have to build a custom container image for that? Even then, how could I add the `settings-override.py` in a data volume during build time when said volume only exists during run time? I'm a bit confused here.
