### ISSUE TITLE
Github pull request not created

### ISSUE THREAD

**Issue by anuj-scanova** [WeblateOrg/weblate#8108]
### Describe the issue

I have a self-hosted Weblate running on an EC2 instance using docker.

I want the weblate to create a pull request to the `master` branch once in a private repository.

Here is my VCS configuration for the project
<img width="1021" alt="Screen Shot 2022-09-12 at 3 00 58 PM" src="https://user-images.githubusercontent.com/105233146/189620905-ac2e56af-4338-42f7-aabd-3f0a0c56390f.png">

Settings in the `docker-compose.override.yml` is
```
version: '3'
services:
  weblate:
    ports:
      - 8000:8080
    environment:
      WEBLATE_ALLOWED_HOSTS: translate.example.io
      WEBLATE_SITE_TITLE: Project i18n
      WEBLATE_SITE_DOMAIN: translate.example.io
      WEBLATE_REGISTRATION_OPEN: 1
      WEBLATE_TIME_ZONE: UTC
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_REQUIRE_LOGIN: 1
      WEBLATE_GITHUB_USERNAME: anuj-org
      WEBLATE_GITHUB_TOKEN: ghp_IxMejxxxxxxxxxxxxxxx
      DEFAULT_COMMITER_EMAIL: translate@scanova.io
      WEBLATE_DEFAULT_COMMITER_NAME: Project i18n
```

Where `anuj-org` is the existing user in Github Organization who has access to all repositories and can create pull requests

Instead of creating a pull request, weblate is pushing changes to the branch and gives the following error
```
Could not push the repository.
Weblate could not push changes to the upstream repository.

remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: This branch must not contain merge commits.        
To github.com:org/website.git
 ! [remote rejected] refactor/angular -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:org/website.git'
 (1)
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Pull request should be created

### How do you run Weblate?

Docker container

### Weblate versions

```
 * Weblate: 4.13.1
 * Django: 4.0.5
 * siphashc: 2.1
 * translate-toolkit: 3.7.1
 * lxml: 4.6.5
 * Pillow: 9.1.1
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.0
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.7.1
 * jellyfish: 0.9.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.13
 * weblate-language-data: 2022.5
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.1
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.6.0
 * Cython: 0.29.30
 * misaka: 2.1.1
 * GitPython: 3.1.27
 * borgbackup: 1.2.1
 * pyparsing: 3.0.9
 * pyahocorasick: 1.4.4
 * python-redis-lock: 3.7.0
 * charset-normalizer: 2.1.0
 * Python: 3.10.5
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.24.21
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.1.4
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.7
 * PostgreSQL server: 14.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.ap-south-1.amazonaws.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-1019-aws (aarch64)
```
